pinterest/querybook

docs_website/package.json, docs_website/src/components/HomePage/AnnouncementSection/index.jsx, docs_website/src/components/HomePage/AnnouncementSection/index.scss, docs_website/src/pages/index.js, docs_website/yarn.lock
added a banner to link up coming blog post on the docs site. The placeholder URL is google.com
=> docs: add announcement banner on main site

querybook/webapp/components/AppAdmin/AdminMetastore.tsx, querybook/webapp/components/DataDoc/DataDocCellControl.tsx, querybook/webapp/components/Task/TaskEditor.tsx
Fix acl validation.
Fix cron/recurruence validation
=> fix: fix form validation for metastore form

querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/components/QueryRunButton/QueryRunButton.tsx, querybook/webapp/lib/sql-helper/sql-lexer.ts
=> fix: update adhoc query editor to show selection

querybook/webapp/__tests__/lib/utils/cron.test.ts, querybook/webapp/components/DataDocSchedule/DataDocScheduleForm.tsx, querybook/webapp/components/Task/TaskEditor.tsx, querybook/webapp/lib/utils/cron.ts, querybook/webapp/ui/ReccurenceEditor/RecurrenceEditor.tsx
=> ui: add yearly and hourly scheduling

querybook/webapp/components/DataTableView/DataTableView.scss, querybook/webapp/components/DataTableView/DataTableView.tsx
looks same in modal & is centered like a datadoc in non-modal view
=> ui: add max width to table view

querybook/webapp/ui/ErrorPage/ErrorPage.tsx
=> ui: add margin to error page

querybook/webapp/__tests__/ui/__snapshots__/ErrorPage.test.js.snap, querybook/webapp/components/AccessRequestButton/AccessRequestButton.tsx, querybook/webapp/components/DataDocAccessRequestPermissionPicker.tsx/DataDocAccessRequestPermissionPicker.scss, querybook/webapp/components/DataDocAccessRequestPermissionPicker.tsx/DataDocAccessRequestPermissionPicker.tsx, querybook/webapp/components/DataDocViewersList/DataDocViewersList.scss, querybook/webapp/components/DataDocViewersList/DataDocViewersList.tsx
before:
Owner:
after:
Requester:
Owner:
closes #350
=> ui: add request edit access + style update

querybook/webapp/ui/Form/FormField.scss, querybook/webapp/ui/ReccurenceEditor/RecurrenceEditor.tsx
=> ui: add recurrence editor error

querybook/webapp/ui/ReccurenceEditor/RecurrenceEditor.tsx
=> ui: update hourly blurb

querybook/server/app/datasource.py, querybook/webapp/lib/data-doc/datadoc-socketio.ts, querybook/webapp/lib/socketio-manager.ts
flask abort does not disconnect socket properly. So use disconnect from socketio instead
also added proper frontend message to show to users
=> Update authentication issue with socketio

querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx, querybook/webapp/components/DataTableViewQueryExample/DataTableViewQueryExamples.tsx, querybook/webapp/components/DataTableViewSourceQuery/DataTableViewSourceQuery.tsx, querybook/webapp/ui/CodeHighlight/CodeHighlight.tsx, querybook/webapp/ui/CodeHighlight/ThemedCodeHighlight.tsx, querybook/webapp/ui/CopyPasteModal/CopyPasteModal.scss
- Fix code highlighter not using the right editor theme in QueryCell
- Add SeeMoreText in StatementResultError
- Prevent horizontal and vertical overflow for copy paste modal
=> fix:small ui issues

querybook/webapp/components/UserBadge/UserAvatar.tsx, querybook/webapp/components/UserSelect/UserSelect.tsx
Now user select will have a profile picture 
Also updated the default icon color picking logic so different colors can be picked even if the letters are different
=> feat: show user name in user select

querybook/scripts/bundled_docker_run_web, querybook/webapp/components/DataDoc/DataDoc.tsx
also fixed the setup process for yan install
=> fix: show untitled datadoc

querybook/webapp/components/UserSelect/UserSelect.tsx
UserSelect wrongly passes a react component as username on select. This fixes the issue
=> Fix username ui display

k8s/scheduler-deployment.yaml, k8s/web-deployment.yaml
Please check this issue!
https://github.com/pinterest/querybook/issues/560
Thank you!
=> fix: change remaining querybook image url

querybook/webapp/components/DataDoc/DataDoc.tsx, querybook/webapp/components/QueryView/QueryView.tsx, querybook/webapp/hooks/useLoader.ts
- Fix page crash on datadoc deletion
- Fix access denied page not showing up
=> fix: Delete DataDoc and QueryExecutionAccess errors

.github/workflows/publish.yml, package.json
Instead of publishing to github, publish the prod image to dockerhub
=> feat: change workflow to publish to dockerhub

docs_website/docs/integrations/add_result_store.md
=> fix: add explanation about mandatory environment variables

querybook/webapp/components/AppAdmin/AppAdmin.tsx, querybook/webapp/components/AppRouter/AppRouter.tsx, querybook/webapp/components/DataDocSchemaNavigator/DataDocSchemaNavigator.tsx, querybook/webapp/components/EmbeddedQueryPage/EmbeddedQueryPage.tsx, querybook/webapp/components/EnvironmentAppRouter/EnvironmentAppRouter.tsx, querybook/webapp/components/EnvironmentAppRouter/EnvironmentModalSwitchRouter.tsx, querybook/webapp/components/EnvironmentAppRouter/mainRoute/BoardRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/mainRoute/DataDocRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/ChangeLogRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/DataTableRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/InfoMenuRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/QueryExecutionRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/SearchRoute.tsx, querybook/webapp/components/EnvironmentAppRouter/modalRoute/UserSettingsMenuRoute.tsx, querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.tsx, querybook/webapp/components/EnvironmentsRouter/EnvironmentsRouter.tsx, querybook/webapp/components/Landing/Landing.tsx, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/components/QuerySnippetRoute/QuerySnippetRoute.tsx
Optimization stats (minimized, gzipped):
Original: 1.9mb
With codesplit:
admin page: 1.2mb
adhoc: 1.4mb
datadoc: 1.6mb
datatable: 1.7mb
all: 1.9mb
=> ui: add code splitting to webapp

.storybook/webpack.js, querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/ui/CodeHighlight/CodeHighlight.stories.tsx, querybook/webapp/ui/CodeHighlight/CodeHighlight.tsx
- Added height property for codeHighlight to prevent overflow hidden. 
- Added storybook story to preview
=> fix: update overflow property of codehighlight, added stories

docker-compose.yml, querybook/scripts/runservice
Add run flower command to runservice
Added an example docker compose setup for celery flower
=> feat: add celery flower monitoring example

docs_website/docs/developer_guide/storybook.md, docs_website/docusaurus.config.js, docs_website/package.json, docs_website/sidebars.json, docs_website/yarn.lock
=> docs: Add documentation for storybook

querybook/server/lib/query_analysis/templating.py, querybook/tests/test_lib/test_query_analysis/test_templating.py
simplified the regex expression to avoid necessary backtrack
=> fix: regex backtracking due to nesting

querybook/server/datasources/search.py, querybook/webapp/components/Search/SearchDatePicker.scss, querybook/webapp/components/Search/SearchDatePicker.tsx, querybook/webapp/components/Search/SearchOverview.scss, querybook/webapp/components/Search/SearchOverview.tsx
- Frontend fix: update UI logic that hides date picker when date is selected
- Backend fix: update es search query (we should have unit test this in future)
=> fix: search date picker logic

querybook/server/lib/result_store/stores/file_store.py, querybook/tests/test_lib/test_result_store/test_stores/test_file_store.py
Closes #599 
Added unit tests for file store. Cleaned up code to remove unnecessary csv writer and mkdir.
=> fix: update file store behavior for better csv parsing

package.json, querybook/webapp/lib/chart/chart-meta-processing.ts, yarn.lock
Use the beginAtZero option to start at 0 whenever possible. If it is negative, then ignore that option.
=> fix: let y axis auto provide scale

querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/const/keyMap.ts, querybook/webapp/lib/codemirror/index.ts
Now you can press Alt-1, Alt-2, ... Alt-9 to change the engine in the query cell
=> feat: add shortcut to change the engine

package.json, webpack.config.js, yarn.lock
looks like removing the length in content hash solves the problem
=> fix: production web is broken due to css name mapping in source map 

querybook/webapp/components/StatementResultTable/StatementResultTableColumn.tsx, querybook/webapp/lib/query-result/detector.ts, querybook/webapp/lib/query-result/transformer.tsx
=> feat:add json view in table results

querybook/webapp/__tests__/ui/__snapshots__/KeyboardKey.test.js.snap, querybook/webapp/components/DataDoc/DataDoc.tsx, querybook/webapp/components/DataDoc/DataDocCellControl.tsx, querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/QueryRunButton/QueryRunButton.tsx, querybook/webapp/const/keyMap.ts, querybook/webapp/lib/utils/keyboard.ts, querybook/webapp/ui/KeyboardKey/KeyboardKey.tsx
=> feat: add copy and paste shortcuts

querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/components/QueryEditor/QueryEditor.scss, querybook/webapp/components/QueryEditor/QueryEditor.tsx, querybook/webapp/components/QuerySnippetComposer/QuerySnippetComposer.tsx, querybook/webapp/components/QuerySnippetInsertionModal/QuerySnippetView.tsx, querybook/webapp/components/QueryView/QueryViewEditor.tsx
Now you can full screen adhoc queries and query executions
=> feat: add full screen button for query editors

querybook/server/datasources/search.py, querybook/webapp/components/DataDocNavigator/DataDocGridItem.scss, querybook/webapp/components/DataDocNavigator/DataDocGridItem.tsx, querybook/webapp/components/DataTableNavigator/DataTableHoverContent.scss, querybook/webapp/components/DataTableNavigator/DataTableHoverContent.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx, querybook/webapp/components/DataTableViewMini/TablePanelView.tsx, querybook/webapp/hooks/redux/useDataTable.ts, querybook/webapp/redux/dataTableSearch/types.ts, querybook/webapp/ui/Popover/PopoverHoverWrapper.tsx
Hovering over docs
Hovering over tables
=> feat: add hover to display functionality for docs and tables

querybook/server/datasources_socketio/query_execution.py, querybook/server/logic/datadoc.py
Error 1: Trying to update a data cell after its removed from a data doc
Error 2: trying to access progress when progress it not defined
=> fix: common exceptions thrown in server

querybook/server/logic/datadoc.py
Previously only the subquery is ordered, which doesn't guarantee the order of the final results
=> fix: add ordering by impression when fetching recent data docs

querybook/webapp/components/AppAdmin/AdminUserRole.tsx, querybook/webapp/components/DataTableView/DataTableHeader.tsx, querybook/webapp/components/UserBadge/UserAvatar.tsx, querybook/webapp/components/UserBadge/UserName.tsx, querybook/webapp/components/UserEnvironmentEditor/UserEnvironmentEditor.tsx, querybook/webapp/components/UserMenu/UserMenu.tsx, querybook/webapp/const/user.ts, querybook/webapp/const/userRoles.ts, querybook/webapp/redux/user/action.ts, querybook/webapp/redux/user/reducer.ts, querybook/webapp/redux/user/types.ts, querybook/webapp/resource/user.ts
- Remove all user related api and refactored them into resource. Once this PR is landed, I will refactor more api actions into resources
- Remove redux logout since we refresh the page on logout, there is no need to complicate the behavior
=> fix: Remove logout from redux, add user resource

querybook/server/datasources/query_execution.py, querybook/webapp/components/DataDocStatementExecutionBar/ResultExportDropdown.tsx, querybook/webapp/resource/queryExecution.ts
The parameter should be exporter name not export name
=> fix: exporter name parameter correction

querybook/webapp/__tests__/ui/Table.test.js, querybook/webapp/__tests__/ui/__snapshots__/AsyncButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Table.test.js.snap, querybook/webapp/components/DataDocStatementExecutionBar/DataDocStatementExecutionBar.tsx, querybook/webapp/components/DataDocViewersBadge/DataDocViewersBadge.tsx, querybook/webapp/components/QueryEngineStatusButton/QueryEngineStatusButton.tsx, querybook/webapp/components/QueryExecutionButton/QueryExecutionButton.tsx, querybook/webapp/components/QueryRunButton/QueryRunButton.tsx, querybook/webapp/components/QueryViewNavigator/QueryViewFilter.tsx, querybook/webapp/components/UnauthPage/UnauthPage.tsx, querybook/webapp/lib/utils/index.ts, querybook/webapp/ui/AsyncButton/AsyncButton.tsx, querybook/webapp/ui/InfinityScroll/InfinityScroll.tsx, querybook/webapp/ui/Link/Link.tsx, querybook/webapp/ui/Table/Table.tsx, querybook/webapp/ui/Timer/Timer.tsx
Pure Components -> React.memo function components
There should be no functionality change except removal of unused logic
=> refactor: Convert some components from class to function

querybook/webapp/components/DataDocHoverContent/DataDocHoverContent.tsx, querybook/webapp/components/DataDocNavigator/DataDocGridItem.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigator.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigatorBoardItem.scss, querybook/webapp/components/DataDocNavigator/DataDocNavigatorBoardItem.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigatorBoardSection.scss, querybook/webapp/components/DataDocNavigator/DataDocNavigatorBoardSection.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigatorSection.scss, querybook/webapp/components/DataDocNavigator/navigatorConst.ts, querybook/webapp/hooks/redux/useDataDoc.ts, querybook/webapp/hooks/redux/useDataTable.ts, querybook/webapp/ui/Popover/Popover.tsx
- Update indent of list item to make them more visible
- When list is expanded, added a hover bg color to highlight it (light bg is used to indicate it is hovered) 
- When you hover over list item, it would show the tooltip for more details
=> fix: ui updates to list in datadoc nav

querybook/webapp/components/AppAdmin/AdminAnnouncement.tsx, querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.tsx, querybook/webapp/components/QueryExecution/ExecutedQueryCell.tsx, querybook/webapp/components/QueryExecution/QueryExecution.tsx, querybook/webapp/redux/querybookUI/action.ts, querybook/webapp/resource/admin/announcement.ts
1. Announcement should be pulled from announcement endpoint, not admin announcement endpoint
2. Do not allow paste in editor if you cannot edit
=> fix: small ui bugs

README.md, docs_website/docs/integrations/add_auth.md, querybook/server/app/auth/github_auth.py, querybook/server/app/auth/oauth_auth.py, webpack.config.js
Now users can use GitHub oauth client to login. Also updated documentation
closes #653
=> feat: Add GitHub Oauth

querybook/webapp/components/DataDocCell/DataDocCell.tsx
There is no need to ask for confirm if the content of the cell is empty
=> fix: Skip confirmation for cell deletion if it is empty

docs_website/docs/integrations/add_auth.md, querybook/server/app/auth/azure_auth.py, querybook/server/env.py
Add support for azure_auth. Update docs with an example for azure_auth. 
This is tested and we(Razorpay) have been running this in production for more than 3 months now.
=> Add support for azure auth

querybook/server/lib/query_analysis/templating.py
Issue before: metastore loader is always fetched when templatizing query, even if it is not needed.
Now: metastore loader will be only initialized when it is needed, and only once
=> fix: Lazy load metastore loader

querybook/server/clients/glue_client.py, querybook/server/clients/hms_client.py, querybook/server/lib/metastore/base_metastore_loader.py, querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py, querybook/server/lib/metastore/loaders/hive_metastore_loader.py, querybook/server/lib/query_analysis/templating.py, querybook/tests/test_lib/test_metastore/test_loaders/test_glue_data_catalog_loader.py, querybook/tests/test_lib/test_query_analysis/test_templating.py, requirements/base.txt
closes #650
Minor improvements to `latest_partition` template function
* Make partition key optional when table has only one partition column
* Allow passing conditions to filter latest partition
* Allow added `latest_partition` function to a recursive template variable
=> fix: Improve latest_partition template function

querybook/server/lib/query_executor/executor_factory.py, querybook/server/lib/query_executor/executor_template/templates.py, querybook/server/lib/utils/execute_query.py
=> Allow users to specify proxy_user_indetifier for Presto Engine. 

querybook/server/lib/query_executor/base_executor.py
Otherwise the update would be useless
=> fix: Only update meta if it is not None

docs_website/docs/setup_guide/connect_to_query_engines.md, querybook/server/lib/query_executor/all_executors.py, querybook/server/lib/query_executor/base_executor.py, querybook/server/lib/query_executor/clients/trino.py, querybook/server/lib/query_executor/connection_string/trino.py, querybook/server/lib/query_executor/executor_template/templates.py, querybook/server/lib/query_executor/executors/trino.py, requirements/base.txt
Integrating an official Trino Plugin for query book backed-up with native Trino-python-client.
Issue Link : **https://github.com/pinterest/querybook/issues/509**
=> Feat : Trino plugin Integration - Querybook

querybook/webapp/components/AppAdmin/AdminAnnouncement.scss, querybook/webapp/components/AppAdmin/AdminAnnouncement.tsx, querybook/webapp/components/AppAdmin/AppAdmin.scss, querybook/webapp/components/AppAdmin/components/EnvironmentSelection/EnvironmentSelection.tsx, querybook/webapp/components/Task/TaskEditor.scss, querybook/webapp/components/Task/TaskEditor.tsx, querybook/webapp/ui/GenericCRUD/GenericCRUD.tsx
Update margin/padding/color of confirm buttons
Updated tooltip message and spacing for announcement form
=> ui: minor updates to admin ui

package.json, querybook/server/datasources/search.py
hits.total is now an object instead of value:
=> fix: small fix to count in es7

docs_website/sidebars.json
Forgot to add it to sidebar in the previous PR
=> fix: add infra installation to sidebar

querybook/webapp/components/TemplateDataDocButton/DataDocTemplateVarForm.tsx
it should be array of array of strings instead of array of strings. Also use simple field to show yup schema validation errors
=> fix: update yup validation schema for template var form

package.json, webpack.config.js, yarn.lock
Need to fix ignoreplugin according to examples on webpack website
=> chore: bump webpack to 5.65

querybook/webapp/__tests__/ui/__snapshots__/KeyboardKey.test.js.snap, querybook/webapp/components/DataDocStatementExecution/StatementLog.scss, querybook/webapp/components/EnvironmentAppSidebar/EnvironmentTopbar.scss, querybook/webapp/components/StatementResultTable/StatementResultTable.tsx, querybook/webapp/index.scss, querybook/webapp/lib/codemirror/editor_styles.scss, querybook/webapp/stylesheets/_html.scss, querybook/webapp/stylesheets/_variables.scss, querybook/webapp/ui/KeyboardKey/KeyboardKey.tsx
=> ui: font update

querybook/webapp/components/Task/TaskStatus.tsx
=> chore: fix a typo

docs_website/docusaurus.config.js, docs_website/package.json, docs_website/src/components/HomePage/HeaderSection/index.jsx, docs_website/yarn.lock
Have to upgrade docusaurus to latest and include sass as a package
=> docs: fix build pipeline

querybook/webapp/components/QueryViewNavigator/QueryResult.tsx, querybook/webapp/components/QueryViewNavigator/QueryViewNavigator.scss, querybook/webapp/const/queryExecution.ts, querybook/webapp/lib/utils/datetime.ts
Hide user name
Change Execution -> Run
Show run time for completed queries
Show tooltip for how long ago
=> ui: update query execution run ui

querybook/webapp/__tests__/ui/__snapshots__/CopyButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Dropdown.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Icon.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/IconButton.test.js.snap, querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx, querybook/webapp/components/EnvironmentAppSidebar/EnvironmentTopbar.scss, querybook/webapp/ui/Button/IconButton.scss, querybook/webapp/ui/Button/IconButton.tsx, querybook/webapp/ui/Checkbox/Checkbox.scss, querybook/webapp/ui/Icon/Icon.scss, querybook/webapp/ui/Icon/Icon.tsx, querybook/webapp/ui/Select/Select.scss, querybook/webapp/ui/Tabs/Tabs.scss
=> ui: add more accent

querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.scss, querybook/webapp/components/EnvironmentAppRouter/modalRoute/SearchRoute.tsx, querybook/webapp/components/QueryComposer/QueryComposer.scss, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/components/QueryComposer/QueryComposerExecution.tsx, querybook/webapp/components/QueryExecution/QueryError.tsx, querybook/webapp/components/QueryExecution/QueryExecution.scss, querybook/webapp/components/QueryExecution/QueryExecution.tsx, querybook/webapp/components/QueryExecutionBar/QueryExecutionBar.scss, querybook/webapp/components/QueryExecutionBar/QueryExecutionBar.tsx, querybook/webapp/components/Search/SearchOverview.scss, querybook/webapp/components/Search/SearchOverview.tsx, querybook/webapp/components/Search/SearchResultItem.scss, querybook/webapp/components/Search/SearchResultItem.tsx, querybook/webapp/components/Search/TableSelect.tsx, querybook/webapp/index.scss, querybook/webapp/scss_variables.scss, querybook/webapp/ui/Card/Card.scss, querybook/webapp/ui/Checkbox/Checkbox.scss, querybook/webapp/ui/Modal/Modal.scss, querybook/webapp/ui/Modal/Modal.tsx, querybook/webapp/ui/Tag/Tag.scss
=> ui: update search modal

querybook/webapp/components/Announcements/Announcements.scss, querybook/webapp/components/BoardList/BoardList.scss, querybook/webapp/components/BoardList/BoardList.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigator.tsx, querybook/webapp/components/DataDocSchemaNavigator/DataDocSchemaNavigator.scss, querybook/webapp/components/DataDocViewersList/ViewerPermissionPicker.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx, querybook/webapp/components/EnvironmentAppSidebar/EntitySidebar.tsx, querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.scss, querybook/webapp/components/Landing/Landing.scss, querybook/webapp/components/Landing/Landing.tsx, querybook/webapp/components/QueryComposer/QueryComposer.scss, querybook/webapp/components/QuerySnippetNavigator/QuerySnippetNavigator.tsx, querybook/webapp/components/QueryViewNavigator/QueryResult.tsx, querybook/webapp/components/QueryViewNavigator/QueryViewFilter.tsx, querybook/webapp/components/QueryViewNavigator/QueryViewNavigator.scss, querybook/webapp/components/QueryViewNavigator/QueryViewNavigator.tsx, querybook/webapp/components/UIGuide/QuerybookSidebarUIGuide.tsx, querybook/webapp/components/UserSettingsMenu/UserSettingsMenu.tsx, querybook/webapp/stylesheets/_variables.scss, querybook/webapp/ui/Button/IconButton.scss, querybook/webapp/ui/Popover/Popover.scss, querybook/webapp/ui/Popover/Popover.tsx, querybook/webapp/ui/StatusIcon/StatusIcon.scss, querybook/webapp/ui/Tag/Tag.scss, querybook/webapp/ui/Tag/Tag.tsx
+ sidebar changes
+ variable updates
=> ui: update adhoc, landing, and anns

querybook/webapp/lib/query-result/transformer.tsx
JSON.prettify does not work with BigInt, use JSONBig instead
=> fix: big int prettify json

package.json, querybook/server/datasources/datadoc.py
get my data docs wasn't working because in https://github.com/pinterest/querybook/pull/732 the API for get_data_doc_by_user now also returns count
=> fix: get_data_doc_by_user is returning count

querybook/server/app/auth/ldap_auth.py
fixes https://github.com/pinterest/querybook/issues/759
=> fix: double username transformation in ldap authorizer

.storybook/webpack.js, docs_website/docs/changelog/breaking_change.md, jest.config.js, package.json, querybook/server/app/auth/__init__.py, querybook/server/app/auth/oauth_auth.py, querybook/webapp/components/UserLoader/UserLoader.tsx, querybook/webapp/lib/utils/global.ts, querybook/webapp/resource/user.ts, querybook/webapp/types.d.ts, webpack.config.js
Fixing the #761 .
This fix adds one env var on the UI to apply a redirection only on Development mode.
This fix makes by default the next_url to be the PUBLIC_URL informed for proper redirection after callback execution.
=> Feat - OAuth on Development Mode (Hot Reload ON)

querybook/server/datasources/datadoc.py, querybook/server/logic/datadoc.py, querybook/server/logic/schedule.py, querybook/tests/test_lib/test_data_doc/test_data_cell.py, querybook/webapp/components/DataDocSchedule/DataDocScheduleRunLogs.tsx, querybook/webapp/components/DataDocScheduleList/DataDocName.tsx, querybook/webapp/components/DataDocScheduleList/DataDocScheduleActionButtons.tsx, querybook/webapp/components/DataDocScheduleList/DataDocScheduleItem.scss, querybook/webapp/components/DataDocScheduleList/DataDocScheduleItem.tsx, querybook/webapp/components/DataDocScheduleList/DataDocScheduleList.scss, querybook/webapp/components/DataDocScheduleList/DataDocScheduleList.tsx, querybook/webapp/components/DataDocScheduleList/HumanReadableCronSchedule.tsx, querybook/webapp/components/DataDocScheduleList/LastRecordRunTime.tsx, querybook/webapp/components/DataDocScheduleList/LastRun.tsx, querybook/webapp/components/DataDocScheduleList/NextRun.tsx, querybook/webapp/components/DataDocScheduleList/cronHelper.tsx, querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.tsx, querybook/webapp/components/Task/TaskStatusIcon.tsx, querybook/webapp/const/schedule.ts, querybook/webapp/redux/scheduledDataDoc/action.ts, querybook/webapp/redux/scheduledDataDoc/reducer.ts, querybook/webapp/redux/scheduledDataDoc/types.ts, querybook/webapp/redux/store/types.ts, querybook/webapp/resource/dataDoc.ts, querybook/webapp/resource/taskSchedule.ts, querybook/webapp/ui/Title/Title.tsx
More clear pagination control
Added filters to allow only show scheduled
Better card view
=> feat: Rewrite scheduled docs UI

querybook/webapp/components/DataTableViewSamples/DataTableViewSamples.tsx
=> ui: Add icons, change accent for samples

querybook/webapp/index.html
Loading screen was overflowing because of height issue
=> fix: splash screen height

querybook/webapp/ui/Button/IconButton.tsx, querybook/webapp/ui/Icon/Icon.scss, querybook/webapp/ui/Icon/Icon.tsx, querybook/webapp/ui/Icon/LucideIcons.ts
=> fix: loading icon typing

querybook/webapp/components/DataDocStatementExecutionBar/ResultExportDropdown.tsx, querybook/webapp/components/DataDocStatementExecutionBar/ResultExportSuccessToast.tsx
* Fix UI for completed export (remove success duration, fix css)
=> fix: fix async exporter UI issues

querybook/webapp/__tests__/ui/__snapshots__/Checkbox.test.js.snap, querybook/webapp/components/DataDocSchemaNavigator/DataDocSchemaNavigator.scss, querybook/webapp/components/DataTableNavigator/SchemaTableView/SchemaTableItem.tsx, querybook/webapp/components/DataTableView/DataTableHeader.scss, querybook/webapp/components/DataTableView/DataTableHeader.tsx, querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.scss, querybook/webapp/components/DataTableViewMini/DataTableViewMini.tsx, querybook/webapp/components/DataTableViewSamples/DataTableViewSamples.tsx, querybook/webapp/components/Token/TokenCreation.tsx, querybook/webapp/ui/Checkbox/Checkbox.tsx
small misalignment + margin fixes
=> ui: bug fix

querybook/webapp/__tests__/ui/__snapshots__/AsyncButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Button.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/CopyButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Dropdown.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/ListMenu.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Message.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Pagination.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/SimpleReactSelect.test.js.snap, querybook/webapp/components/AccessRequestButton/AccessRequestButton.tsx, querybook/webapp/components/DataDoc/DataDocError.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigatorSection.tsx, querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigator.scss, querybook/webapp/components/DataTableViewMini/DataTableViewMini.tsx, querybook/webapp/components/ExecutionPicker/QueryExecutionPicker.tsx, querybook/webapp/components/QueryView/QueryView.scss, querybook/webapp/components/UserBadge/UserAvatarList.tsx, querybook/webapp/components/UserBadge/UserBadge.scss, querybook/webapp/ui/CopyPasteModal/CopyPasteModal.tsx, querybook/webapp/ui/StyledText/StyledText.tsx
=> ui: update execution dropdown

querybook/webapp/__tests__/ui/__snapshots__/AsyncButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Button.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/CopyButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Dropdown.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/ListMenu.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Message.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Pagination.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/SimpleReactSelect.test.js.snap, querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.tsx, querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx, querybook/webapp/components/DataDocStatementExecutionBar/ResultExportDropdown.tsx, querybook/webapp/components/DataDocStatementExecutionBar/ResultExportSuccessToast.tsx, querybook/webapp/components/QueryComposer/QueryComposer.scss, querybook/webapp/components/QueryComposer/QueryComposerExecution.tsx, querybook/webapp/components/QueryExecution/QueryExecution.tsx, querybook/webapp/components/QueryExecution/QueryExecutionDuration.tsx, querybook/webapp/components/QueryExecutionBar/QueryExecutionBar.tsx, querybook/webapp/components/QueryView/QueryViewExecution.tsx, querybook/webapp/components/Task/TaskStatusIcon.tsx
=> ui: add back duration

querybook/server/logic/datadoc.py, querybook/webapp/redux/board/action.ts, querybook/webapp/redux/dataDoc/action.ts, querybook/webapp/redux/dataDoc/reducer.ts, querybook/webapp/redux/dataDoc/types.ts
the order was pretty much random before this
=> fix: recent docs order

package.json, querybook/server/lib/export/exporters/gspread_exporter.py, requirements/exporter/gspread.txt
Context: https://github.com/burnash/gspread/issues/524
Updated gspread to the latest version and use USER_ENTERED as input
=> fix: gspread single quote issue

querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx, querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx, querybook/webapp/lib/utils/number.ts
Show commas for row limit choices
=> ui: add comma to result limit

package.json, querybook/server/app/flask_app.py, querybook/server/datasources/query_execution.py, querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.tsx, querybook/webapp/redux/queryExecutions/action.ts
fetchResult logic would report the wrong number for limit, which makes useEffect infinite load the query result. This PR should fix the issue
=> fix: DDOS query result

querybook/server/app/datasource.py, querybook/server/app/flask_app.py, querybook/webapp/lib/utils/error.ts, querybook/webapp/redux/queryExecutions/action.ts, requirements/base.txt
- Update limiter library to 2.2.0
- Add header if limiter request fails
- Better error parsing for rate limit errors
=> fix: update limiter logic, frontend error format limiter errors

querybook/server/lib/query_executor/executors/trino.py
@czgu 
im sorry, i did not test different types of error in previous fix
=> fix: separate query errors and engine errors (fixes #826)

docker-compose.yml, package.json
move common fields to yaml variables. Give container name to all the containers
=> chore: update docker-compose definitions

docs_website/docs/configurations/infra_config.md, querybook/config/querybook_default_config.yaml, querybook/server/app/auth/ldap_auth.py, querybook/server/env.py
Opportunity to redefine uid attribute (fixes #833)
=> Opportunity to redefine uid attribute (fixes #833)

querybook/webapp/__tests__/ui/__snapshots__/KeyboardKey.test.js.snap, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterGraph.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterListItem.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterSettings.tsx, querybook/webapp/hooks/dag/useExporterDAG.ts, querybook/webapp/hooks/dag/useSavedDAG.ts, querybook/webapp/lib/data-doc/data-doc-utils.ts, querybook/webapp/lib/utils/keyboard.ts, querybook/webapp/ui/FlowGraph/FlowGraph.scss, querybook/webapp/ui/FlowGraph/FlowGraph.tsx, querybook/webapp/ui/FlowGraph/QueryCellNode.scss, querybook/webapp/ui/FlowGraph/QueryCellNode.tsx, querybook/webapp/ui/FlowGraph/RemovableEdge.tsx, querybook/webapp/ui/Icon/LucideIcons.ts, querybook/webapp/ui/KeyboardKey/KeyboardKey.tsx
- remove edges
- color on update
- vertical/horizontal handles
- hash query
=> ui: add query + updated to queryCellNode

querybook/server/datasources/datadoc.py, querybook/server/lib/data_doc/base_dag_exporter.py, querybook/server/lib/data_doc/dag_exporter/demo_dag_exporter.py, querybook/server/lib/data_doc/utils.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.scss, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterButton.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterForm.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterGraph.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterSettings.tsx, querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx, querybook/webapp/hooks/dag/useExporterDAG.ts, querybook/webapp/hooks/dag/useExporterSettings.ts, querybook/webapp/hooks/dag/useSavedDAG.ts, querybook/webapp/resource/dataDoc.ts, querybook/webapp/ui/FlowGraph/FlowGraph.tsx
- fix meta issue
- hide button unless exporter added
- refactor
- add useTemplatedVariables
- update export flow
=> ui: refactor + hide button

querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterListItem.tsx
=> feat: add theme code editor highlight for preview

querybook/server/datasources/search.py
* Apply AND across tables selected in table names filter in query search
=> fix: Apply AND to table_names filter in query search

docs_website/docs/integrations/add_dag_exporter.md, docs_website/docs/integrations/plugins.md, package.json, querybook/.vscode/settings.json, querybook/migrations/versions/17f7c039ab6e_add_dag_exporter.py, querybook/server/lib/dag_exporter/all_dag_exporter.py, querybook/server/lib/dag_exporter/base_dag_exporter.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterListItem.tsx, querybook/webapp/ui/FlowGraph/QueryCellNode.tsx
=> ui: add title for untitled cells + plug in documentation

querybook/webapp/components/TemplateDataDocButton/DataDocTemplateVarForm.tsx
* fix: update yup validation schema for template var form
* update error msg, force length to be 2
* remove console
=> fix: update yup validation schema for template var form (#713)

package.json, querybook/server/datasources/search.py, querybook/webapp/components/CodeMirrorTooltip/TableTooltip.tsx, querybook/webapp/components/DataTableNavigator/DataTableHoverContent.tsx, querybook/webapp/components/DataTableTags/CreateDataTableTag.tsx, querybook/webapp/components/DataTableTags/DataTableTags.tsx, querybook/webapp/components/DataTableTags/TableTagSelect.scss, querybook/webapp/components/DataTableTags/TableTagSelect.tsx, querybook/webapp/components/Search/SearchResultItem.tsx, querybook/webapp/const/search.ts, querybook/webapp/ui/Tag/HoverIconTag.tsx
- Make tag elasticsearch case sensitive (actually this makes all filter search case sensitive, frontend should handle the case conversion)
- Update invalid tag select ui
- Update tag creation logic, use creatable instead
- Make tag creation case insensitive
- Show tag in search results
- If table tags are readonly, then do not show context menu
- Fixed an issue where clicking on 'x' on tags would propagate the event
=> fix: multiple tag bugs and ui update

package.json, querybook/server/datasources/table_upload.py, querybook/server/lib/metastore/base_metastore_loader.py, querybook/server/lib/table_upload/exporter/base_exporter.py, querybook/server/lib/table_upload/exporter/s3_exporter.py, querybook/server/lib/utils/execute_query.py
- Add function to check metastore directly to see if a table exists
- The if exists action only runs if the table does exist, removes the need to run query
- Shorten the poll interval for execute_query for create table
=> feat: greatly speedup table exporter

package.json, querybook/server/datasources/board.py, querybook/server/datasources/search.py, querybook/webapp/components/Search/SearchResultItem.tsx, querybook/webapp/redux/board/action.ts, querybook/webapp/resource/board.ts
- Remove owner_uid field for board creation
- Remove HTML injection via data doc title
=> fix: security bug issues

querybook/server/lib/export/exporters/gspread_exporter.py, querybook/server/tasks/run_datadoc.py
- Fixed incorrect wipe of gspread auth token
- Make datadoc workflow status account for notification and export
=> fix: datadoc workflow

querybook/webapp/components/DataDocSchedule/DataDocScheduleForm.tsx
- Dedup multiple exporters so that the auth function is only called once
=> fix: unique exporter

querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.scss
=> fix: consistent background highlighting for list header

querybook/server/datasources/search.py, querybook/server/lib/elasticsearch/query_utils.py, querybook/server/lib/elasticsearch/search_datadoc.py, querybook/server/lib/elasticsearch/search_query.py, querybook/server/lib/elasticsearch/search_table.py, querybook/server/lib/elasticsearch/search_utils.py, querybook/server/lib/elasticsearch/suggest_table.py, querybook/server/lib/elasticsearch/suggest_user.py
- Breakdown elasticsearch logic into multiple files
- remove the assumption of running the code at the api level
=> refactor: elasticsearch clean up

docs_website/docs/changelog/breaking_change.md, package.json, querybook/config/elasticsearch.yaml, querybook/server/const/elasticsearch.py, querybook/server/datasources/board.py, querybook/server/datasources/search.py, querybook/server/lib/elasticsearch/query_utils.py, querybook/server/lib/elasticsearch/search_board.py, querybook/server/lib/elasticsearch/search_datadoc.py, querybook/server/lib/elasticsearch/search_query.py, querybook/server/lib/elasticsearch/search_table.py, querybook/server/lib/query_analysis/samples.py, querybook/server/lib/richtext.py, querybook/server/logic/board.py, querybook/server/logic/elasticsearch.py, querybook/server/scripts/es_3_6_0_upgrade.py, querybook/server/tasks/sync_elasticsearch.py, querybook/webapp/components/Search/SearchOverview.tsx, querybook/webapp/components/Search/SearchResultItem.tsx, querybook/webapp/const/search.ts, querybook/webapp/redux/search/action.ts, querybook/webapp/redux/search/types.ts, querybook/webapp/resource/search.ts
- added elasticsearch definitions and query generation
- added search UI
=> feat: add list search to elasticsearch

querybook/webapp/components/DataDoc/DataDoc.tsx, querybook/webapp/components/DataDocTextCell/DataDocTextCell.scss, querybook/webapp/components/Search/SearchDatePicker.tsx, querybook/webapp/lib/utils/index.ts, querybook/webapp/ui/RichTextEditor/RichTextEditor.scss, querybook/webapp/ui/RichTextEditor/RichTextEditor.tsx, querybook/webapp/ui/RichTextEditorToolBar/LinkInput.tsx, querybook/webapp/ui/RichTextEditorToolBar/RichTextEditorToolBar.tsx
- move DataTextCell css to richTextEditor
- fix issue with selection box updates 
- fix issue with autofocus of links not working
=> fix: rich text editor issues

querybook/webapp/components/Board/Board.tsx, querybook/webapp/components/Board/BoardBoardItem.tsx, querybook/webapp/components/Board/BoardDataDocItem.tsx, querybook/webapp/components/Board/BoardDataTableItem.tsx, querybook/webapp/components/Board/BoardItem.tsx, querybook/webapp/components/Board/BoardQueryItem.tsx, querybook/webapp/components/BoardExpandableSection/BoardExpandableSection.tsx, querybook/webapp/components/BoardRightSidebar/BoardRightSidebar.tsx, querybook/webapp/context/BoardPage.ts, querybook/webapp/hooks/board/useBoardItemActions.ts
- no ui change
- refactored drag and deletion hooks for full page view
- general refactor to rid of duplicated key error
=> feat: add drag and drop for list reordering

requirements/engine/bigquery.txt
=> fix: Pin protobuf to 3.20.1

querybook/server/datasources/datadoc.py, querybook/server/logic/datadoc.py, querybook/server/tasks/sync_es_queries_by_datadoc.py
- create new celery tasks to update queries (cells & execs) by datadoc idea
- create new celery tasks to update query cells by datadoc idea
=> fix: combine update es queries by datadoc id into one celery task

querybook/webapp/components/Board/Board.tsx, querybook/webapp/components/BoardRightSidebar/BoardRightSidebar.tsx, querybook/webapp/components/DataDoc/DataDoc.tsx, querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx, querybook/webapp/components/UIGuide/BoardItemTourSteps.tsx, querybook/webapp/components/UIGuide/BoardTourSteps.tsx, querybook/webapp/components/UIGuide/DataDocUIGuide.tsx, querybook/webapp/ui/Dropdown/Dropdown.scss, querybook/webapp/ui/Dropdown/Dropdown.tsx
=> ui: move tutorials to sidebar

querybook/webapp/components/QueryEditor/QueryEditor.tsx, querybook/webapp/const/keyMap.ts, querybook/webapp/lib/codemirror/custom-commands.ts
Hi! We want to add the next functionality https://kencenerelli.wordpress.com/2018/03/25/visual-studio-code-multi-line-and-multi-cursor-editing/ .
So, a user can edit multiple lines at the same time and a user can set multiple selections.
=> Feat: add Multi-line and multi-cursor editing

querybook/server/app/auth/okta_auth.py
Fixes #942.
This PR updates `OktaLoginManager` to request the OIDC scope `profile`, which includes the user's name. 
Relevant sections of the parent class `OAuthLoginManager` were overridden as needed, to avoid impacting the other authentication strategies or custom auth plugins.
=> feat: Update Okta auth method to provide full names

querybook/webapp/__tests__/ui/__snapshots__/Link.test.js.snap, querybook/webapp/components/AdminAppSidebar/AdminAppNavigator.tsx, querybook/webapp/components/BoardExpandableList/BoardExpandableHeader.tsx, querybook/webapp/components/BoardExpandableList/BoardListItemRow.tsx, querybook/webapp/components/DataDocNavigator/DataDocGridItem.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx, querybook/webapp/components/DataTableNavigator/SchemaTableView/SchemaTableItem.tsx, querybook/webapp/components/QueryEditor/QueryEditor.tsx, querybook/webapp/const/metastore.ts, querybook/webapp/ui/Link/Link.tsx
- Removed unnecessary `<Link />` onClicks for 
- Added drag and drop url behavior
- Separated table row into a separate component
https://user-images.githubusercontent.com/8283407/182265532-d347aa5c-f7ab-4a81-a7c0-2cdbe0dd4fe2.mov
=> feat: add table name drop and drop

querybook/webapp/components/Board/Board.tsx, querybook/webapp/components/Board/BoardBoardItem.tsx, querybook/webapp/components/Board/BoardBreadcrumbs.scss, querybook/webapp/components/Board/BoardBreadcrumbs.tsx, querybook/webapp/components/Board/BoardWrapper.tsx, querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx, querybook/webapp/components/EnvironmentAppRouter/mainRoute/BoardRoute.tsx, querybook/webapp/hooks/ui/useBoardPath.ts
This is a work in progress PR to add breadcrumb to querybook
=> feat: Add breadcrumb for board in querybook

package.json, querybook/webapp/components/AppRouter/AppRouter.tsx, querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.tsx, querybook/webapp/components/QueryComposer/QueryComposerExecution.tsx, querybook/webapp/components/QueryExecutionBar/QueryExecutionBar.tsx, querybook/webapp/components/QueryView/QueryViewExecution.tsx
- Unify permalink generation logic for execution
- If no trailing slash, automatically append one
=> fix: auto add trailing slash at end

querybook/webapp/components/Board/BoardBoardItem.tsx, querybook/webapp/components/Board/BoardDataDocItem.tsx, querybook/webapp/components/Board/BoardItem.tsx, querybook/webapp/components/Board/BoardQueryItem.tsx
=> ui: add board author, make title into a link

docs_website/docs/integrations/add_table_upload.md, package.json, plugins/table_uploader_plugin/__init__.py, querybook/config/querybook_default_config.yaml, querybook/server/clients/hms_client.py, querybook/server/clients/s3_client.py, querybook/server/datasources/metastore.py, querybook/server/datasources/table_upload.py, querybook/server/env.py, querybook/server/lib/metastore/base_metastore_loader.py, querybook/server/lib/query_analysis/create_table/base_create_table.py, querybook/server/lib/query_analysis/create_table/create_table.py, querybook/server/lib/query_analysis/create_table/languages/hive.py, querybook/server/lib/query_analysis/create_table/languages/presto.py, querybook/server/lib/table_upload/exporter/base_exporter.py, querybook/server/lib/table_upload/exporter/exporter_factory.py, querybook/server/lib/table_upload/exporter/s3_exporter.py, querybook/server/lib/table_upload/importer/importer_factory.py, querybook/tests/test_lib/test_query_analysis/test_create_table/test_languages/test_hive.py, querybook/tests/test_lib/test_query_analysis/test_create_table/test_languages/test_presto.py, querybook/webapp/components/TableUploader/TableUploaderConfirmForm.tsx, querybook/webapp/components/TableUploader/TableUploaderForm.tsx, querybook/webapp/resource/table.ts
- Added plugin model for table upload exporters
- Make S3 exporter support getting path from HMS
- Added warning checks before uploading table
- Support uploading external or managed table
=> feat: improve table upload with managed/external

docs_website/docusaurus.config.js, docs_website/package.json, docs_website/src/components/HomePage/AnnouncementSection/index.jsx, docs_website/yarn.lock
Updated to the latest version. Updated Algolia according to requirements. Removed announcement banner
=> fix: docs website failed to build

docs_website/docs/developer_guide/run_db_migration.md
=> docs: update migration description

querybook/server/app/auth/password_auth.py
=> Add message to error

querybook/webapp/components/ConfirmationManager/ConfirmationMessage.tsx, querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- Remove Limit selector, query transpiler if the doc is read only
- rename reject to cancel
=> fix: disable new features in read only mode

package.json, requirements/base.txt, yarn.lock
Update them to the latest version
=> chore: update websocket packages version

querybook/webapp/components/QueryComposer/RunQuery.tsx, querybook/webapp/components/QuerySnippetComposer/QuerySnippetComposer.tsx
because the promise was not rejected
=> fix: delete button stuck in spinning for cancel confirm

querybook/webapp/__tests__/lib/utils/index.test.ts, querybook/webapp/lib/utils/index.ts, querybook/webapp/ui/Link/Link.tsx
changed to regex since the previous one would capture json for some reason
also added some unit tests to show its capability
=> fix: url validation

package.json, querybook/server/lib/query_executor/clients/presto.py, querybook/server/lib/query_executor/clients/trino.py, querybook/server/lib/query_executor/clients/utils/presto_cursor.py, querybook/server/lib/query_executor/clients/utils/presto_types.py, querybook/tests/test_lib/test_query_executor/test_clients/test_utils/test_presto_types.py, querybook/webapp/lib/query-result/detector.ts, querybook/webapp/lib/query-result/transformer.tsx, querybook/webapp/lib/utils/boolean.ts, yarn.lock
Solves #514
The information about subfields in nested structures is obtained from Presto&Trino, it's just not used and the current result isn't very readable.
This pull requests suggests:
- Leveraging cursor description in order to compose JSON with names of subfields for nested structures and storing it in the result CSV.
- Using a `ReactJson` component in order to display the JSON information in user-friendly fashion on the front-end.
```sql
SELECT
CAST(
ROW(
1,
'tp',
ROW('xxx'),
MAP(ARRAY [0.123456789], ARRAY [0.1]),
timestamp '2012-10-31 01:00 UTC',
INTERVAL '2' DAY,
ARRAY ['aa', 'bb', 'cc'],
IPADDRESS '10.0.0.1'
) AS ROW(
id int,
name varchar,
nested ROW(x varchar),
map map(decimal(38, 12), decimal(38, 5)),
d TIMESTAMP WITH TIME ZONE,
i INTERVAL DAY TO SECOND,
arr ARRAY(varchar),
ip …
```
=> feat: display presto and trino nested structures

docs_website/docs/integrations/customize_html.md, plugins/webpage_plugin/custom_script.ts, querybook/webapp/components/DataDocStatementExecution/ErrorSuggestion.tsx, querybook/webapp/components/QueryExecution/QueryError.tsx, querybook/webapp/lib/query-result/error-suggestion.ts, querybook/webapp/types.d.ts, querybook/webapp/ui/Message/Message.scss
You can now insert a custom error message whenever there is a query error
=> feat: (experimental) make error suggestion pluggable

package.json, querybook/webapp/lib/query-result/detector.ts, querybook/webapp/lib/query-result/transformer.tsx, yarn.lock
- Ignore string json
- Auto convert big number to string when serialized to not lose precision
=> fix: JSONView fix

package.json, querybook/webapp/components/DataDocScheduleList/NextRun.tsx, yarn.lock
Fixes #997 by replacing `@datasert/cronjs-matcher` with `cron-parser`.
=> fix: Replace cronjs-matcher with cron-parser

querybook/webapp/components/QueryEditor/QueryEditor.tsx, querybook/webapp/lib/sql-helper/sql-autocompleter.ts, querybook/webapp/lib/sql-helper/sql-context-sensitive-linter.ts
If the client side never fetch the data table before, the column auto completion wont work. This change is to prefetch all the tables in the query no matter user picked it from auto completion list or typed themselves.
=> fix: table column auto completion not work sometimes

querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/components/QueryEditor/BoundQueryEditor.tsx, querybook/webapp/components/QueryEditor/QueryEditor.tsx
Refactor `QueryEditor` from class component to functional component.
=> refactor: QueryEditor to functional component

querybook/webapp/components/QueryEditor/QueryEditor.tsx
**Issues**:
1. `getLintAnnotations` gets called too many times
2. adhoc qurey: can't delete, can only append
**Cause**:
1. `getLintAnnotations` will be triggered on either 
* `performLint` gets called. We have `debounce` on performLint, so it's okay.
* when `editorOptions` changes. When `value` changes, it will update `formatQuery`, which will also update `editorOptions` as it depends on `formatQuery`.  So basically every change on the query, it will trigger a lint call. 
2. we passed `onBlur` and `onKeyDown` directly to `<ReactCodeMirror />`, while for the ad-hoc query, it doesn't pass down these two props, which causes exception.
**Fix**
1. add a debounce on `getLintAnnotations` as well
2. check the `onBlur` and `onKeyDown` before calling it.
=> fix: query editor issues after refactor

querybook/webapp/components/TemplateGuide/guides/syntax.md, querybook/webapp/lib/codemirror/index.ts, querybook/webapp/ui/CodeHighlight/ThemedCodeHighlight.tsx, querybook/webapp/ui/CodeHighlight/ThemedCodeHighlightWithMark.tsx, querybook/webapp/ui/Markdown/Markdown.tsx, querybook/webapp/ui/Markdown/MarkdownCode.tsx
=> feat: Add syntax highlight/copy to markdown code

querybook/webapp/components/QueryEditor/QueryEditor.tsx, querybook/webapp/lib/codemirror/codemirror-mode.ts, querybook/webapp/lib/codemirror/editor_styles.scss, querybook/webapp/lib/codemirror/index.ts
=> feat: syntax highlighting for templated queries

querybook/server/lib/dag_exporter/base_dag_exporter.py, querybook/server/lib/dag_exporter/export_dag.py, querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/const/datadoc.ts, querybook/webapp/hooks/dag/useExporterSettings.ts, querybook/webapp/resource/dataDoc.ts
some updates to the dag exporter
* change the exporter type `text` to `code`
* update the returned export data with some additional fields like `name`, `success`, `msg`, `url` and `code`
* add a new modal component to render the returned export data
=> feat: update base and demo dag exporter

package.json, querybook/webapp/components/QueryComposer/QueryComposer.tsx, querybook/webapp/hooks/useForwardedRef.ts, querybook/webapp/ui/Markdown/MarkdownCode.tsx
issue is caused by useForwardedRef, it doesn't actually update when ref changes
=> fix: formatQuery isn't using the latest ref

querybook/server/lib/dag_exporter/base_dag_exporter.py, querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/context/DataDocDAGExporter.ts, querybook/webapp/hooks/dag/useExporterSettings.ts, querybook/webapp/redux/dataDoc/action.ts, querybook/webapp/redux/dataDoc/reducer.ts, querybook/webapp/redux/dataDoc/types.ts
address comments from https://github.com/pinterest/querybook/pull/1045 after merging.
=> address comments from PR 1045

querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/ui/FlowGraph/GraphControls.tsx, querybook/webapp/ui/FlowGraph/QueryCellNode.tsx, querybook/webapp/ui/Modal/Modal.scss, requirements/base.txt
=> ui: update dag exporter

querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx, querybook/webapp/ui/FlowGraph/GraphControls.tsx, querybook/webapp/ui/FlowGraph/QueryCellNode.tsx, querybook/webapp/ui/Modal/Modal.scss
Reverts pinterest/querybook#1050
=> Revert "ui: update dag exporter"

package.json, querybook/webapp/lib/sql-helper/sql-autocompleter.ts
right now, the setter errors out because "this" is null
=> fix: SqlAutocompler setter not bind

querybook/server/lib/dag_exporter/all_dag_exporter.py, querybook/webapp/ui/Markdown/MarkdownCode.tsx
=> ui: update markdown code copy button

querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterListItem.tsx, querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterSettings.tsx
* remove the unused `Use Templated Variables` form section
* disable the query popover for now, will revisit the design
=> fix: [dag exporter] remove use vairables

querybook/server/lib/event_logger/__init__.py, querybook/server/lib/event_logger/base_event_logger.py, querybook/server/lib/event_logger/loggers/db_event_logger.py, querybook/server/lib/event_logger/loggers/null_event_logger.py
Add an allow and block list to filter unnecessary api logging.
=> feat: add filter support for api logging

querybook/webapp/components/QueryComposer/QueryComposer.scss
=> fix: search and replace overlaps with lint status

querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.scss, querybook/webapp/components/ExecutionPicker/QueryExecutionPicker.tsx
=> ui: fix execution date string

package.json, querybook/server/const/event_log.py, querybook/server/datasources_socketio/helper.py, querybook/server/lib/event_logger/__init__.py, querybook/server/lib/event_logger/base_event_logger.py
Log websocket messages from client by event logging, like api logging.
=> feat: add websocket logging

querybook/webapp/components/DataTableView/DataTableView.tsx
no logic change, just refactored DataTableView to hooks
=> chore: refactor DataTableView to hooks

querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx, querybook/webapp/components/QueryRunButton/QueryRunButton.scss, querybook/webapp/components/QueryRunButton/QueryRunButton.tsx, querybook/webapp/components/Search/SearchOverview.scss, querybook/webapp/const/uiConfig.ts, querybook/webapp/ui/SearchBar/SearchBar.scss, querybook/webapp/ui/SearchBar/SearchBar.tsx
- Changed from clear button to 'x'
Before:
After:
- this makes the component fit better with small filter bars: 
- removed unnecessary css
- fix: Added white background for searchbar when in engine picker
- only show column filter if there are more than 5 columns
=> ui: Update searchbar css

querybook/webapp/resource/queryExecution.ts
Suppress the exceptions from query linting with toast.
=> chore: not notify on query linting exceptions

querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.tsx
removed unnecessary checks
do not show progress if it is undefined
=> refactor: progress ui

querybook/webapp/components/QueryExecutionAccessList/QueryExecutionAccessList.scss, querybook/webapp/components/UserBadge/UserBadge.tsx, querybook/webapp/components/UserSelect/UserSelect.tsx, querybook/webapp/ui/ViewersList/ViewersList.scss
=> ui: fix overflow for long usernames

package.json, yarn.lock
It will fix the issue https://github.com/sql-formatter-org/sql-formatter/issues/534
=> chore: upgrade sql-formatter

querybook/server/lib/utils/color.py, querybook/server/logic/tag.py
* Forgot to revert the hard coded color value for testing
* Also add checking for None before finding the nearest color
=> fix: find nearest color

docs_website/docs/setup_guide/helm_guide.md, docs_website/sidebars.json
Add helm deployment document based on request #682.
=> docs: add helm deployment guide

querybook/server/app/datasource.py, querybook/server/app/db.py, querybook/server/clients/redis_client.py, querybook/server/datasources_socketio/connect.py, querybook/server/datasources_socketio/helper.py, querybook/server/lib/stats_logger/__init__.py, querybook/server/lib/stats_logger/all_stats_loggers.py, querybook/server/lib/stats_logger/base_stats_logger.py, querybook/server/lib/stats_logger/loggers/console_stats_logger.py, querybook/server/lib/stats_logger/loggers/null_stats_logger.py, querybook/server/tasks/all_tasks.py, querybook/server/tasks/run_query.py
- add tags support
- update some metrics name
=> feat: update stats metrics names and add tags

package.json, querybook/webapp/__tests__/ui/__snapshots__/AsyncButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Box.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Button.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Center.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Column.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Container.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Content.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/CopyButton.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/DisabledSection.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Dropdown.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/FullHeight.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/KeyboardKey.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Level.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Link.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/ListMenu.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Loader.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Loading.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Menu.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Message.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Pagination.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/QuerybookLogo.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/ResizableTextArea.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/SimpleReactSelect.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/Table.test.js.snap, querybook/webapp/__tests__/ui/__snapshots__/ToolBarButton.test.js.snap, requirements/base.txt, yarn.lock
upgrade below packages
- styled-components
- webpack
- numpy
=> chore: updgrade some packages

querybook/server/logic/data_element.py, querybook/webapp/components/Search/EntitySelect.tsx
also change the data element search by substring instead of prefix, but put the prefix ones in the begining
=> fix: make entity select creatble be false by default

querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.scss, querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx, querybook/webapp/components/Search/EntitySelect.scss, querybook/webapp/components/Search/EntitySelect.tsx, querybook/webapp/stylesheets/_utilities.scss
=> ui: show full description on hover

querybook/webapp/components/DataDocLeftSidebar/DataDocLeftSidebar.tsx, querybook/webapp/components/DataDocNavigator/DataDocNavigator.tsx, querybook/webapp/components/DataDocRightSidebar/DeleteDataDocButton.tsx, querybook/webapp/hooks/dataDoc/useDeleteDataDoc.ts
=> ui: enable remove datadoc from sidebar

querybook/webapp/components/DataDocNavigator/DataDocGridItem.tsx
=> ui: show last updated if untitled doc

querybook/server/const/comment.py, querybook/server/datasources/comment.py, querybook/server/logic/comment.py, querybook/server/logic/comment_permission.py
QQQs
- should i add permission checks for adding comments?
- should users be allowed to delete comments? should they be completely deleted or archived (and say deleted comment or something like that in UI)
- did i set up the model correctly so that if a Comment was deleted, its corresponding DataTableComment or DataCellComment would be deleted? i think i did but just wanna confirm.
=> backend: add comment endpoints

querybook/server/datasources/__init__.py, querybook/server/lib/patch.py
to investigate if this is the cause of some deployment failure
=> fix: disable monkey patch and api plugin

Dockerfile
This reverts commit 68d92f416514b685a09018280bb89d31c6b88d6f.
=> Revert "upgrade nodejs from v16 to v18 (#1267)"

querybook/server/datasources/search.py
remove any space from front + end of search string
=> ui: strip space from search string

querybook/server/lib/elasticsearch/search_table.py
Increase golden table weight and decrease ngram weight to boost golden tables in table search
=> Update table search boost scores

package.json
for PR: https://github.com/pinterest/querybook/pull/1325
=> bump version for ai-assistant and vector store

docker-compose.yml
added shielding in plugins.security.disabled: 'true'
=> fix: Update docker-compose.yml - added shielding

querybook/server/app/flask_app.py
Patching a temp hotfix to resolve worker's timeout issue.
=> fix: hotfix for worker starting up

package.json, querybook/server/app/flask_app.py
Follow recommendated cookie [settings](https://flask.palletsprojects.com/en/1.1.x/security/#set-cookie-options) to prevent CSRF-prone requests
=> fix: update cookie config

querybook/webapp/components/DataDocViewersList/DataDocViewersList.tsx
- Fix querybook edit access issue
- Bug when converting a private doc with read-only collaborators to public
Test Plan:
https://github.com/pinterest/querybook/assets/41878611/03aa6d32-b294-4b36-8838-a10964438ffb
=> Fix: querybook edit access issue

package.json, querybook/webapp/components/AIAssistant/AICommandResultView.tsx
add back the text2sql survey, which was missing in the PR: https://github.com/pinterest/querybook/pull/1429/
=> fix: add back text2sql survey

containers/bundled_querybook_config.yaml, querybook/server/lib/ai_assistant/assistants/openai_assistant.py
Recommend using GPT-4o and GPT-4o-mini for AI actions
=> feat: Introduce new OpenAI models for Querybook

package.json, yarn.lock
to address the security advisory of `dompurify`: https://github.com/advisories/GHSA-mmhx-hmjr-r674
=> chore: upgrade package of dompurify

querybook/webapp/components/QueryExecutionBar/QueryExecutionBar.tsx, querybook/webapp/components/QueryReviewsNavigator/QueryReviewItem.tsx, querybook/webapp/components/QueryReviewsNavigator/QueryReviewsNavigator.scss, querybook/webapp/components/QueryView/QueryView.tsx, querybook/webapp/components/QueryView/QueryViewExecution.tsx, querybook/webapp/components/QueryViewReview/QueryViewReview.scss, querybook/webapp/components/QueryViewReview/QueryViewReview.tsx, querybook/webapp/components/QueryViewReview/statusUtils.ts, querybook/webapp/components/ReviewIndicatorButton/ReviewIndicatorButton.tsx
- Merge header, content, reason into same block with border radius
- Move requested by and requested review on same line, with review reason on bottom. 
- Reject modal button right aligne and  buttons same colour, move rejection reason to be placeholder instead 
- Query Decision into same block
- Condense reviewer into a badge, on click can uncollapse review details
Pending Review:
Approved: 
Rejected: 
Demo:
https://github.com/user-attachments/assets/5fb64f06-a7ba-4676-9548-310e04797539
=> ui: Reviewer view polish

package.json, querybook/config/querybook_public_config.yaml, querybook/webapp/components/QueryPeerReviewModal/QueryPeerReviewModal.scss, querybook/webapp/components/QueryPeerReviewModal/QueryPeerReviewModal.tsx
to support markdown for the query review modal description and check list.
=> feat: support markdown for the query review modal

.github/workflows/lint.yml, .github/workflows/pythontests.yml, Dockerfile, docs_website/docs/developer_guide/developer_setup.mdx, package.json, requirements/base.txt
The uWSGI issue has been unblocked. 
https://github.com/pinterest/querybook/pull/956
=> chore: upgrade to Python 3.10

README.md
=> chore: add deepwiki badge

querybook/webapp/lib/python/python-provider.tsx
Addressed an issue affecting Windows users where Querybook fails to open with a "STATUS_ACCESS_DENIED" error may due to some recent security or policy changes impacting Pyodide WASM loading. 
This PR implements a workaround by lazy loading Pyodide packages, allowing Querybook to open successfully on Windows. 
Note that this fix does not resolve the underlying Python feature limitations on Windows but unblocks initial access to the application.
=> fix: lazy initializing python kernel
