- querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.tsx
The code to  auto select execution would break because usedQueryParam is false until an executionId is selected. Updated the behavior so usedQueryParam would turn to true after executionId in query param is not found
``` useEffect(() => {
selectExecutionIndex(0);
}, [queryExecutions.length]);
```
> fix: auto query selection behavior

- requirements/base.txt
These updates account for allowing client_options to be passed to the
google auth client, which allows credentials to be provided via json
instead of ENV vars.
> fix: update google packages.

- docker-compose.yml
Closes #493 
Tested on mac and ubuntu.
> fix: Update nofile ulimit for docker to be 65536 to enable es

- README.md
- docs_website/docusaurus.config.js
- docs_website/src/components/HomePage/HeaderSection/index.jsx
The URL didn't point to the join URL.
> fix: Fix Slack URL

- README.md
- docs_website/docs/setup_guide/connect_to_query_engines.md
- querybook/webapp/components/AppAdmin/AdminQueryEngine.tsx
Updated readme to link to the list of supported engines.
Updated the docs to show engines in a table
Updated the language picker in the Admin UI, now query engines are capitalized by default
> docs: update docs section for query engines

- querybook/config/datadoc.yaml
- querybook/webapp/components/DataDoc/DataDocCellControl.tsx
Read cellType title from 'name' field of 'datadoc.yaml' for better UI customizations, such as using alternative terms or translating into other languages.
> Modify cellType title

- querybook/webapp/components/CreateDataDocButton/CreateDataDocButton.tsx
- querybook/webapp/components/Info/Tours.tsx
- querybook/webapp/hooks/dataDoc/useCreateDataDoc.ts
We do not allow datadocs to be created without a query engine (otherwise the default query cell would not work), however the error previously was confusing. I have added a frontend check instead to show a more understandable error.
> fix: Meaningful error when creating a datadoc in env without query engine

- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
Closes #492
I can't find a good solution for this issue, although the chances of happening are rare. So I lowered the debounce value so that the redux store can save more frequently before navigation.
> fix: lower debounce for query cell

- querybook/webapp/components/DataDocChartCell/DataDocChart.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx
- querybook/webapp/lib/chart/chart-data-processing.ts
since `chartData` should be the data used for both the bar color & legend, we can assume that it's being updated correctly. according to what i've read updating the legend requires an `update` but i guess the color change doesn't necessarily need one for bar/horiz bar/bubble charts. (+ also found the legend doesn't update for bubble charts)
> ui: fix chart legend color update lag

- querybook/webapp/components/DataTableView/DataTableView.scss
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/ui/Container/Container.scss
- use flex to center children
- use flex:1 for children so they would take the whole max width
- remain container inside container
> fix: Force content in container to take full width

- querybook/webapp/__tests__/ui/__snapshots__/Pagination.test.js.snap
- querybook/webapp/redux/search/types.ts
- querybook/webapp/ui/Pagination/Pagination.scss
- querybook/webapp/ui/Pagination/Pagination.tsx
make it so that the next/prev buttons are only shown when applicable
make ellipses only appear when applicable
> ui: update pagination

- querybook/server/app/datasource.py
- querybook/server/const/data_doc.py
- querybook/server/datasources_socketio/__init__.py
- querybook/server/datasources_socketio/connect.py
- querybook/server/datasources_socketio/datadoc.py
- querybook/server/datasources_socketio/helper.py
- querybook/server/datasources_socketio/query_execution.py
- querybook/server/logic/datadoc_collab.py
- querybook/webapp/lib/socketio-manager.ts
- Refactored socket io datasource code
- Require socket.io connection to be always authenticated
- Debounce the error message on disconnect event, if they are reconnected with 2 seconds, then do not show the error message to the user
> fix: Improve socketio error handling behaivor

- querybook/webapp/lib/socketio-manager.ts
- Rename sendToast function for socketio
- if reason is client disconnect, then do not show error message
> fix: hide client disconnect error msg

- querybook/webapp/ui/Content/Content.scss
> ui: Add markdown table css table for content

- querybook/server/datasources/search.py
- querybook/server/logic/elasticsearch.py
Remove parsing of host and port since the python elasticsearch library also does parsing. With the parsing removed, users can specified more details in the connection string such as https and username/password
Now users can connect to https traffic via naive connection type.
> fix: simplify es connection logic

- requirements/base.txt
Looks like this PR in python-socketio 5.3.0 broken the websocket connection for Querybook
https://github.com/miguelgrinberg/python-socketio/commit/2538df8bcf0e44881a7653cc684f985252c7fce0
Stack trace:
```
web_1            | Traceback (most recent call last):
web_1            |   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
web_1            |   File "/usr/local/lib/python3.7/site-packages/socketio/pubsub_manager.py", line 164, in _thread
web_1            |     self._handle_emit(data)
web_1            |   File "/usr/local/lib/python3.7/site-packages/socketio/pubsub_manager.py", line 116, in _handle_emit
web_1            |     callback=callback)
web_1            |   File "/usr/local/lib/python3.7/site-packages/socketio/base_manager.py", line 161, in emit …
```
> fix: set version of python-socketio to 5.2.1

- README.md
- querybook/server/clients/glue_client.py
- querybook/server/lib/metastore/loaders/__init__.py
- querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py
- querybook/tests/test_lib/test_metastore/test_loaders/test_glue_data_catalog_loader.py
- requirements/base.txt
- requirements/dev.txt
Implements the feature request proposed in #543 
* Added an AWS Glue Data Catalog client wrapper using boto3
* Added a BaseMetastoreLoader implementation specific to the AWS Glue Data Catalog
* Added unit test for the newly implemented GlueDataCatalogLoader and used moto to mock remote AWS Glue resources
https://user-images.githubusercontent.com/9784890/118569150-a01b4680-b779-11eb-9e88-e1896a1c6337.mov
> feat: add aws glue data catalog as a metastore

- querybook/server/lib/query_executor/clients/hive.py
- querybook/tests/test_lib/test_query_executor/test_clients/test_hive_progress_percentage.py
- querybook/tests/test_lib/test_query_executor/test_hive_progress_percentage.py
Fixes pinterest/querybook#552
Just added a check if progressPercentage is reported by thrift response. If yes, Hive Client uses it to calculate percentage. It falls back on original method of calculating based on map/reduce progress. Added unit tests.
> feat: support progressPercentage in hive thrift response 

- querybook/server/lib/metastore/loaders/sqlalchemy_metastore_loader.py
- querybook/server/lib/query_executor/clients/sqlalchemy.py
- querybook/server/lib/query_executor/connection_string/sqlalchemy.py
- querybook/server/lib/query_executor/executor_template/templates.py
- querybook/server/lib/utils/json.py
- querybook/tests/test_lib/test_query_executor/test_connection_string/test_sqlalchemy.py
- querybook/webapp/ui/SmartForm/SmartForm.scss
- querybook/webapp/ui/SmartForm/SmartForm.tsx
Closes #541
Add support for admins to specify connect_args that will be sent to create_engine. Available for SqlAlchemyExecutor as well as SqlAlchemyMetastoreLoader
Also for ExpandableFormField, if the value is null, the frontend would set it to empty array so it can be modifiable
> feat: Add query params for sqlalchemy connection

- k8s/web-deployment.yaml
- k8s/web-service.yaml
- k8s/worker-deployment.yaml
1. Without initdb and initweb options, web will not start properly and cannot start db.
2. LoadBalancer is unnecessary, we can use ClusterIP
3. OOM will occur with current limit
All these commits have been tested already through my own k8s cluster.
> fix: change k8s options to operate

- querybook/webapp/ui/Link/Link.tsx
- querybook/webapp/ui/Markdown/Markdown.tsx
Now right click, middle click would not trigger the custom link handler.
Updated the style of the link to make it more obvious in the markdown
Hovered
> fix: make link left click only, update style

- README.md
the previous one expired. This one should last as long as possible.
> fix: slack invite url

- querybook/webapp/components/Search/SearchOverview.scss
- querybook/webapp/ui/Container/Container.scss
Container overflow was clipped because justify-content: center didn't handle overflow well. Use pseudo elements with margin auto instead.
Stackoverflow reference: https://stackoverflow.com/questions/34184535/change-justify-content-value-when-flex-items-overflow-container
> fix: container ui overflow issue

- querybook/server/datasources/query_execution.py
Since flask stream download is prone to breaking, share the URL directly with the user instead
> fix: redirect user for download instead of proxy

- querybook/server/datasources/datadoc.py
- querybook/server/datasources_socketio/datadoc.py
- querybook/server/lib/data_doc/data_cell.py
- querybook/server/logic/datadoc.py
- querybook/server/logic/datadoc_collab.py
- querybook/webapp/components/DataDoc/DataDoc.tsx
- querybook/webapp/components/DataDocCell/DataDocCell.tsx
- querybook/webapp/lib/batch/batch-manager.ts
- querybook/webapp/lib/data-doc/datadoc-socketio.ts
- querybook/webapp/redux/dataDoc/action.ts
- querybook/webapp/redux/dataDoc/reducer.ts
- querybook/webapp/redux/dataDoc/types.ts
- querybook/webapp/redux/dataDocWebsocket/dataDocWebsocket.ts
- Error for updating cell will show properly, and the error message will display
- Insert is now server side idempotent. If the server sends multiple insert. Only the last one will be applied
- delete is now idempotent, both server send and client send event will only be processed once
> fix: error handling for update cell, insert/delete idempotent

- docs_website/docs/integrations/add_lineage.md
- docs_website/docs/integrations/plugins.md
- docs_website/sidebars.json
- querybook/config/querybook_default_config.yaml
- querybook/server/datasources/metastore.py
- querybook/server/env.py
- querybook/server/lib/lineage/db.py
- querybook/server/lib/lineage/utils.py
- querybook/server/logic/demo.py
- querybook/server/logic/elasticsearch.py
- querybook/server/logic/lineage.py
- querybook/server/logic/metastore.py
- querybook/server/tasks/log_query_per_table.py
There are a number of open source data governance platforms available.
Some of the most popular ones are:
* Amundsen: https://www.amundsen.io/
* Atlas: https://atlas.apache.org/
* Marquez: https://marquezproject.github.io/marquez/
They all have data lineage functionality that is exposed via APIs.
This refactor will enable user to replace the default lineage backend.
> refactor: moving lineage code into its own plugin

- querybook/config/datadoc.yaml
- querybook/server/lib/data_doc/data_cell.py
- querybook/tests/test_lib/test_data_doc/test_data_cell.py
- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx
Make sure backend meta validation would handle float and int as expected. This means
actual: int, expected: float would pass validation
actual: float, expected: int would fail the validation
The old validation logic remains as is.
For frontend, make sure hiddenSeries uses chartData instead of query data to account for transformations.
> fix: chart metadata handling issue

- docker-compose.yml
This problem has started occurring after my latest mac update. Docker version 20.10.7
However, putting the variables in quotes fixes this problem. Also tested the fix in ubuntu with version 19.03.13
> fix: docker compose fail due to variable missing

- docs_website/docs/changelog/2020-11-30.md
- docs_website/docs/changelog/breaking_change.md
- docs_website/sidebars.json
- package.json
- querybook/server/datasources/query_execution.py
- querybook/server/lib/result_store/__init__.py
- querybook/server/lib/result_store/stores/base_store.py
- querybook/server/lib/result_store/stores/db_store.py
- querybook/server/lib/result_store/stores/file_store.py
- querybook/server/lib/result_store/stores/google_store.py
- querybook/server/lib/result_store/stores/s3_store.py
Since we redirect user to download file directly, s3 signed url requires a content disposition for custom name. Added this change along with documentation which is a breaking change for plugins.
> major: add ability to customize download name

- querybook/config/datadoc.yaml
- querybook/webapp/components/DataDocChartCell/DataDocChart.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartCell.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.scss
- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartWrapper.tsx
- querybook/webapp/const/dataDocChart.ts
- querybook/webapp/lib/chart/chart-meta-processing.ts
Now you can set the size of the Querybook chart. This would be useful for graphs that have a lot of metrics.
Sizing options:
small <- 30vh
medium <- 60vh
large <- 90vh
auto <- same as before
> feat: added size attribute to chart meta

- package.json
- querybook/webapp/components/DataDocChartCell/DataDocChart.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartCell.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartWrapper.tsx
- querybook/webapp/components/ImpressionWidget/ImpressionWidgetMenu.tsx
- querybook/webapp/lib/chart/chart-meta-processing.ts
- yarn.lock
Fixed multiple bugs related to chartjs 3 update
1. Updated axis config for impressions chart
2. Fixed time axis display with moment adapter
3. Fixed chart sizing to default to auto
4. Fixed axis ticks issue when there are no ticks to display
> fix: multiple charting bugs

- querybook/webapp/lib/chart/chart-data-processing.ts
If the date is a time string, do no processing and let moment handle the parsing
> fix: Use moment to parse date

- package.json
- querybook/server/datasources/datadoc.py
- querybook/webapp/lib/batch/datadoc-save-manager.ts
- querybook/webapp/lib/data-doc/datadoc-socketio.ts
This change will reduce the amount of information send via websockets and rely on HTTP instead which has a much larger limit on size. Using HTTP is also more reliable to prevent loss of work.
Potential future work items:
1. Use HTTP on the send side, and use ws for the receive side
2. Allow ways to send partial information between clients and servers to reduce the data load
> fix: use http instead of ws to updateCell

- querybook/server/app/datasource.py
- querybook/server/datasources/metastore.py
- querybook/webapp/__tests__/lib/utils/error.test.ts
- querybook/webapp/components/DataDoc/DataDoc.tsx
- querybook/webapp/components/DataDocCell/DataDocCell.tsx
- querybook/webapp/lib/utils/error.ts
1. Hide traceback in error responses to make the actual error message more readable
2. traceback is still viewable as "traceback" field for debugging
3. added formatError for toast.error logging to enable better error message
> fix: hide stack trace for users

- querybook/server/datasources/search.py
- querybook/webapp/redux/dataTableSearch/action.ts
Phrase match allows much more accurate result if the table name is directly pasted. Also boost the full name match more than ngram match as it returns much more accurate results. 
On the client side, if the schema name is extracted then we remove it from the keywords to avoid duplication
> fix: use phrase match to improve table name search

- querybook/server/datasources/search.py
- querybook/server/logic/elasticsearch.py
- querybook/webapp/redux/dataTableSearch/action.ts
Use phrase query to boost exact table name matching
Adjust boost score calculation so it never goes below 1 
Remove schema name replacement to provide better proximate for exact name matching
> feat: Fine tuning the search table behavior

- querybook/webapp/components/DataDocChartCell/DataDocChart.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx
- querybook/webapp/const/dataDocChart.ts
- querybook/webapp/lib/chart/chart-utils.ts
Using category axis for timeseries in bar charts would cause the date range to collapse. Now we allow time scale x axis.
Also updated the auto detect display so it shows the correct behavior
> fix: add time scale for bar charts

- querybook/webapp/components/App/App.tsx
- querybook/webapp/components/ImpressionWidget/ImpressionWidgetMenu.tsx
it is not a good fix. But to ensure code splitting, we should import chartjs adapter only when necessary :/
> Add moment adapter for impression charts

- package.json
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/TemplateQueryView/TemplatedQueryView.scss
- querybook/webapp/components/TemplateQueryView/TemplatedQueryView.tsx
- querybook/webapp/hooks/useResource.ts
closes #638 
Users can preview rendered query before running it.
Note you can run directly in modal after viewing the query
If the query failed to render, then the original query is shown
> feat: Add modal to preview templated query

- querybook/webapp/components/Board/BoardDataTableItem.tsx
- querybook/webapp/components/CodeMirrorTooltip/CodeMirrorTooltip.tsx
- querybook/webapp/components/DataDocNavigator/DataDocNavigator.tsx
- querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx
- querybook/webapp/components/Landing/Landing.tsx
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/hooks/redux/useShallowSelector.ts
- querybook/webapp/hooks/redux/useUserQueryEditorConfig.ts
The shallowEquals useSelector prevents unnecessary re-rendering of React components if the useSelector creates a new object
> refactor: use shallowEquals for useselector

- docs_website/docs/user_guide/faq.md
- querybook/server/datasources/query_execution.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py
- querybook/server/lib/metastore/loaders/hive_metastore_loader.py
- querybook/server/lib/query_analysis/templating.py
- querybook/server/tasks/run_datadoc.py
- querybook/tests/test_lib/test_query_analysis/test_templating.py
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/QuerySnippetInsertionModal/QuerySnippetView.tsx
- querybook/webapp/components/TemplateDataDocButton/DataDocTemplateVarForm.tsx
- querybook/webapp/components/TemplateQueryView/TemplatedQueryView.tsx
- querybook/webapp/lib/templated-query/index.ts
- querybook/webapp/resource/queryExecution.ts
closes #635 
Add templated function to get the latest partition of a table.
Users can use this function by adding `{{ latest_partition('schema_name.table_name', 'partition_key') }}` to their queries.
Error messages:
1. Cannot get metastore_loader (or engine_id is not provided)
2. Partition key provided is invalid
3. Full table name is improperly formatted
> feat: Add latest_partition template function

- docs_website/docs/integrations/customize_html.md
- querybook/webapp/redux/dataTableSearch/reducer.ts
- querybook/webapp/types.d.ts
Email: oleksandr_vasylenko2@epam.com
There is a commit for adding a possibility to set up a default value for DataTable page.
After this commit we can set up this code in custom_script.tsx
```window.DATA_TABLE_SEARCH_CONFIG = {
calculateInitialState: (initialState) => ({
...initialState,
searchFilters: {
golden: true
}
})
}
to set up the filter `Featured` as true by default. 
Thank you!
> minor: Set up filters as true by default.

- requirements/base.txt
After conversation with @czgu in slack, I found out that snowflake-connector-python should be specified in order to prevent an error.
Previously, snowflake-connector-python was version 2.4.5 in Querybook, and it created this error:
`(certifi 2021.5.30 (/usr/local/lib/python3.7/site-packages), Requirement.parse('certifi<2021.0.0'), {'snowflake-connector-python'})`
By specifying version to 2.6.1, everything worked fine in my production environment. This version was selected after reviewing the version that was used by Apache Superset. 
Currently we only use snowflake-sqlalchemy for our requirements, but since snowflake-connector-python is included as a dependency, we should also specify the version to prevent any issues. 
Related Issue: …
> fix: specify snowflake-connector-python version

- k8s/README.md
- k8s/scheduler-deployment.yaml
- k8s/web-deployment.yaml
- k8s/worker-deployment.yaml
Sorry, I should have fixed this earlier.
Since Querybook has its image on Docker Hub now, I am replacing the image to use Docker Hub and update README.
> fix: Change docker image and update README

- .github/workflows/publish.yml
Right now only full semver is used, so people can use querybook/querybook:2.8.3. But we want to support both
querybook/querybook:2.8 and querybook/querybook:2 as well
> ci: set patch, minor, major when publishing to docker

- docs_website/docs/setup_guide/connect_to_query_engines.md
We should update the `querybook` docs to point Amazon Redshift users toward using [`redshift_connector`](https://github.com/aws/amazon-redshift-python-driver), the Amazon Redshift Python driver, rather than psycopg2 which is designed for use with PostgreSQL.
`sqlalchemy-redshift` now offers a dialect for the Amazon Redshift Python driver,`redshift_connector`. 
`redshift_connector` supports Amazon Redshift specific datatypes (e.g. `SUPER`, `GEOMETRY`, etc.) as well as IAM authentication. 
Attached are screenshots showing an example of using `sqlalchemy-redshift` with `redshift_connector` in querybook to execute some simple statements and generate charts. Given this testing, I've updated the tier for this query engine from `3` to `2`.
Amazon Redshift Engine
Amazon Redshift Metastore
Amazon …
> docs: update Amazon Redshift query engine docs

- querybook/migrations/versions/aceefd7708b6_change_params_for_hive_metastore_loaders.py
- querybook/server/lib/metastore/loaders/form_fileds.py
- querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py
- querybook/server/lib/metastore/loaders/hive_metastore_loader.py
- querybook/server/lib/metastore/loaders/thrifthive_metastore_loader.py
Solving #690
This pull request adds `Load_partitions` boolean switch to the Metastore creation form for `HMSMetastoreLoader` and `HMSThriftMetastoreLoader`.
I've noticed that this switch is already available in `GlueDataCatalogLoader`, so I've decided to extract the form field to a new module and reuse it from there in all three loaders.
- If I just tried to change the form and opened a Metastore page that uses `HMSMetastoreLoader`, the front-end returned following error: `[Immer] Immer only supports setting array indices and the 'length' property` caused by an array of URLs still present in the DB for the loader in `metastore_params` field.
- Therefore, I've included transformation for `HMSMetastoreLoader` loader that changes `metastore_params` into proper dictionary in data migrations. …
> minor: load_partitions for hive metastore loaders

- querybook/server/lib/utils/execute_query.py
- querybook/server/tasks/run_sample_query.py
The error thrown by presto is often not readable unless we parse a cleaner version. Added that for sample queries as well
> feat: Add error message parsing for sample queries

- docker-compose.yml
- docs_website/docs/changelog/breaking_change.md
- docs_website/docs/setup_guide/prod_setup.md
- helm/templates/elasticsearch/elasticsearch-deployment.yaml
- helm/values.yaml
- k8s/elasticsearch-deployment.yaml
- package.json
- querybook/config/elasticsearch.yaml
- querybook/server/datasources/search.py
- querybook/server/logic/elasticsearch.py
- requirements/base.txt
Solving #683 
This pull requests contains:
- Changes in ElasticSearch document mappings and calls to ES client
- Changes in `docker-compose`, `k8s`, `helm` ElasticSearch deployments
- As every deployment uses only one ES server (it doesn't actually create ES cluster there)`discovery.type=single-node` was used. This is necessary in ES7, otherwise it leads to verification of production setup ([bootstrap checks](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html)) and `the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured` error. But these options are good only with proper cluster.
- For `helm` deployment, I've taken the setting of …
> major: migration to es7

- querybook/webapp/redux/dataTableSearch/action.ts
We found a bug that the table loader didn't send the offset parameter and the table list got the same data for each request.
> Fix table loading for more than 100 items

- webpack.config.js
Turns out the errors shown in Overlay are not very useful but a bit confusing for dev experience. Now it is turned off and we can use console instead to inspect errors
> fix: hide error overlay from react fast refresh

- docs_website/docs/configurations/infra_installation.md
- docs_website/docs/setup_guide/connect_to_query_engines.md
- querybook/server/lib/query_executor/all_executors.py
- querybook/server/lib/query_executor/executors/redshift.py
- querybook/server/lib/query_executor/executors/sqlalchemy.py
- requirements/engine/redshift.txt
- requirements/extra.txt
Adds redshift query engine python packages. @czgu -- is the testing provided below and in #693 sufficient for providing this query engine as "tier 1"? if not, I'm more than happy to perform additional testing, just let me know what else you'd like to see :).
Testing
- confirmed querybook `make` executes successfully after adding `-r extra.txt` in `requirements/local.txt`
Testing Screenshots
- Language Specific Autocomplete supported for Amazon Redshift datatypes
- Query execution 
- Query Engine execution provides status in UI
- Query Engine generates logs
- Authentication via IAM is supported
- Federated Authentication via Identity Provider is supported
> feat: add redshift query engine

- querybook/server/lib/query_executor/connection_string/presto.py
- querybook/server/lib/query_executor/connection_string/trino.py
- querybook/server/lib/query_executor/executor_template/templates.py
- querybook/tests/test_lib/test_query_executor/test_connection_string/test_presto.py
- querybook/webapp/components/AppAdmin/AppAdmin.scss
- querybook/webapp/lib/formik/extract-error.ts
- querybook/webapp/ui/Form/FormError.tsx
- querybook/webapp/ui/GenericCRUD/GenericCRUD.scss
- querybook/webapp/ui/GenericCRUD/GenericCRUD.tsx
- webpack.config.js
Fix include:
- Show form error message when executor param is invalid, useful to let users know what needs to be changed.
- Update parsing logic for Presto and Trino so now they can both accept all strings in query parameters
- Added unit tests for presto connection string parsing
- Hide error overlay for frontend
> fix: parsing issue for connection strings of Presto,Trino

- requirements/base.txt
Due to the security issue, this is manually tested
> chore: upgrade celery to 5.2.3

- containers/docker-compose.dev.yml
- containers/docker-compose.prod.yml
- docker-compose.yml
- docs_website/docs/setup_guide/deployment_guide.md
These 2 fields tmpfs and cap_add are not utilized by Querybook at all, removing them for simplicity sake.
> fix: remove unused docker compose fields

- docker-compose.yml
- helm/values.yaml
- k8s/elasticsearch-deployment.yaml
- requirements/base.txt
Context: https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2
> fix: upgrade elasticsearch to 7.16.2 to fix log4j issue

- querybook/webapp/__tests__/ui/__snapshots__/AsyncButton.test.js.snap
- querybook/webapp/__tests__/ui/__snapshots__/Button.test.js.snap
- querybook/webapp/__tests__/ui/__snapshots__/CopyButton.test.js.snap
- querybook/webapp/__tests__/ui/__snapshots__/Pagination.test.js.snap
- querybook/webapp/__tests__/ui/__snapshots__/ToggleButton.test.js.snap
- querybook/webapp/components/ConfirmationManager/ConfirmationMessage.tsx
- querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.scss
- querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx
- querybook/webapp/ui/Button/StyledButton.tsx
- querybook/webapp/ui/GenericCRUD/GenericCRUD.tsx
- querybook/webapp/ui/ToggleButton/ToggleButton.scss
- querybook/webapp/ui/ToggleButton/ToggleButton.tsx
UI looks exactly the same
- Remove default margins for buttons, only keep sibling selector
- Use shared css classes for data doc right sidebar
> refactor: standardize button margin, simplify right sidebar

- querybook/webapp/components/DataDocChartCell/DataDocChartComposer.tsx
- querybook/webapp/ui/SimpleReactSelect/SimpleReactSelect.tsx
The filtering for aggregate.column would move the index of columns, causing it to display the wrong label. This ensures the correct label is displayed.
> fix: index shifting in aggregate chart config

- docs_website/docs/integrations/customize_html.md
- querybook/webapp/__tests__/lib/utils/udf.test.ts
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/components/UDFForm/UDFForm.scss
- querybook/webapp/components/UDFForm/UDFForm.tsx
- querybook/webapp/components/UDFForm/UDFTypeSelect.tsx
- querybook/webapp/lib/codemirror/index.ts
- querybook/webapp/lib/utils/udf.ts
- querybook/webapp/types.d.ts
- querybook/webapp/ui/Form/FormField.tsx
- querybook/webapp/ui/FormikField/CodeEditorField.tsx
- querybook/webapp/ui/FormikField/SimpleField.tsx
Now users can add UDFs easily in Adhoc Query Editor. To do so they need to fill out a form with language and parameters.
You can add UDF in adhoc or query cell
^ note that this shows presto for testing reasons
Currently, this is only added for BigQuery but more can be added as plugins or directly in the OS repo.
Also added unit tests for query generation as well as documentation
> feat: UDF support

- querybook/webapp/components/StatementResultTable/StatementResultTable.tsx
As a QueryBook user we need to be able to review result sets quickly and easily in order to determine if we have the right data sets without exporting.
Right now the use of space can be frustrating to work with and annoying forcing users to do downloads.  Example:
The result screen (resultset) after executing the query will show the amount of free space allocated by the drop down and not the result amount itself.  So if I had 18 records but set 25
it shows space for 25 instead of just 18
> Remove empty space for tables in data docs

- package.json
- querybook/server/lib/query_executor/clients/presto.py
- querybook/server/lib/utils/utils.py
Presto user proxy can be done by passing a different principal user name directly. We will skip modifying the request's auth http header. This should not change any of the existing behaviors
> patch: update Presto proxy auth behavior

- querybook/server/lib/query_analysis/samples.py
When in the Row Samples feature, a user tries to generate samples filtering the data by some float column.
The UI displays a modal error and does not return the information.
By analyzing the API request, the generated query is treating the float column as a string, adding quotes around the value.
> FLOAT column type fails on Row Samples functionality

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/const/keyMap.ts
- querybook/webapp/lib/codemirror/custom-commands.ts
- querybook/webapp/lib/codemirror/index.ts
This is achieved by reusing the sublime keymap implementation provided here: https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/keymap/sublime.js#L271
> feat: add ability to swap lines in QueryEditor

- querybook/webapp/const/keyMap.ts
- querybook/webapp/lib/utils/keyboard.ts
- querybook/webapp/lib/utils/os-platform.ts
cmd+/ is wrongly passed for windows version of codemirror, pass in ctrl+/ instead
> fix: UI update key

- querybook/server/lib/change_log.py
since breaking change is for developers to be aware of, not users
> fix: do not include breaking change for UI change log

- querybook/webapp/__tests__/ui/__snapshots__/KeyboardKey.test.js.snap
- querybook/webapp/components/DataDocLeftSidebar/DataDocLeftSidebar.tsx
- querybook/webapp/components/DataDocScheduleList/DataDocScheduleList.tsx
- querybook/webapp/lib/utils/keyboard.ts
- querybook/webapp/redux/scheduledDataDoc/types.ts
- querybook/webapp/ui/StyledText/StyledText.tsx
- Show tooltip about how to use data doc contents (table of contents) 
- Show Empty message if there are no scheduled docs
- Also remove user select for empty message
- Make keyboard shortcuts slightly more readable
> ui: various ui updates

- docs_website/docs/configurations/infra_config.md
- querybook/server/app/auth/ldap_auth.py
- querybook/server/env.py
- querybook/tests/test_app/test_auth/test_ldap_auth.py
- requirements/test.txt
Solving #691 
This pull request:
- Extends `ldap_auth.py` module by possibility to specify LDAP bind user that can do LDAP search based on a filtering condition and allow/block specific users to access WebUI.
- Handles situations when user enters LDAP `dn` in different format than `uid=...`.
- Backward compatibility is ensured. Logging in directly with full LDAP DN or with uid and `LDAP_USER_DN` set is still possible.
I was stuck little bit on unit tests, because I based them on `mockldap`  library, but then found out it's not installable under Python 3.7.9 in the GitHub workflow, so I created custom mocked responses instead.
> Feat: LDAP bind user and filter

- package.json
- querybook/server/datasources/metastore.py
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- querybook/webapp/redux/dataSources/action.ts
- querybook/webapp/resource/table.ts
Now users can directly make metastore loader load the table:
> feat: Allow users to manually refresh metastore

- package.json
- querybook/webapp/components/AppAdmin/AdminMetastore.tsx
Loader was used which causes the select option to never show up
> fix: Change Loader to loader for admin metastore

- querybook/webapp/ui/Dropdown/Dropdown.scss
- querybook/webapp/ui/Dropdown/Dropdown.tsx
Add pseudo element in between the nested menus so it doesn't collapse unexpectedly
> fix: add pseudo element between nested menus

- querybook/server/lib/utils/import_helper.py
Plugins are loaded from a variable in a module, and if no plugins are specified, a default value may be applied.  The previous behavior only checked for `None`, which does not match an empty list.  This prevents `EmailNotifier` from being loaded as the default notifier plugin:
```
ALL_PLUGIN_NOTIFIERS = []
``` 
This change more broadly matches undefined plugin configurations and applies the defaults (if any).
As far as I can tell, the only impact of this bug is the notifier module, as it's the only one that provides a default plugin list.
> fix: Use default plugins when imported plugins is an empty list

- requirements/engine/redshift.txt
updates Redshift operator dependency to use the latest version of redshit_connector
> chore: upgrade to redshift_connector 2.0.907

- requirements/base.txt
Updating the version of `typing-extensions` to fix this conflicting dependency:
```
ERROR: Cannot install -r requirements/dev.txt (line 5) and typing-extensions==3.7.4.1 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested typing-extensions==3.7.4.1
black 22.3.0 depends on typing-extensions>=3.10.0.0; python_version < "3.10"
```
This also fixes the following error in Python tests:
```
E   ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/typing_extensions.py)
------------------------------- Captured stderr --------------------------------
[2022-04-26 Tue 03:20:10] - /home/runner/work/querybook/querybook/querybook/server/lib/utils/import_helper.py - …
```
> fix: Update typing-extensions to fix dependency mismatch and tests

- querybook/server/lib/query_executor/clients/trino.py
Fixes an issue when running multiple statements using Trino: the cursor accumulates rows in a list that is not reset between statements, so each subsequent statement includes all the rows from previous statements.
> fix: Reset Trino cursor rows between statements

- querybook/server/app/auth/ldap_auth.py
- querybook/tests/test_app/test_auth/test_ldap_auth.py
Proposing adding `:caseExactMatch:` option ([docs](https://ldap.com/ldap-filters/)) to the filter condition when searching for `uid` in the LDAP directory using bind user.
Motivations:
- Username/password combination should be usually validated in case-sensitive manner
- Currently, the `processed_username` from [here](https://github.com/pinterest/querybook/blob/2287943ac80575856e08931c646f91da34eae57d/querybook/server/app/auth/ldap_auth.py#L287) can be the username passed by user directly. Propagation such a user name with wrong case can result in new user in DB, because DB `username` is case-sensitive.
I perceive this more as a bug fix than a change.
> fix: Make username case-sensitive in bind LDAP login

- docs_website/docs/changelog/breaking_change.md
- package.json
- querybook/config/elasticsearch.yaml
- querybook/server/datasources/datadoc.py
- querybook/server/datasources/search.py
- querybook/server/logic/datadoc.py
- querybook/server/logic/elasticsearch.py
- querybook/server/scripts/es_3_5_0_upgrade.py
- querybook/tests/test_lib/test_elasticsearch/test_elasticsearch.py
fixes #865
- add `public` and `readable_user_ids` fields to query_cell and query_execution elasticsearch indices to restrict access to queries on private datadocs
- change elasticsearch item creation functions to allow option to generate/update specific fields
- update `querybook/server/datasources/search.py` to use "must" query to ensure user has access to datadocs & queries that are returned
> fix: restrict access to private queries in query search

- querybook/server/datasources/board.py
- querybook/server/logic/board.py
- querybook/webapp/components/BoardDetailedList/BoardDetailedList.scss
- querybook/webapp/components/BoardDetailedList/BoardDetailedList.tsx
- querybook/webapp/components/DataDocListsButton/DataDocListsButton.tsx
- querybook/webapp/components/DataDocListsModal/DataDocListsModal.tsx
- querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/components/DataTableViewLists/DataTableViewLists.tsx
- querybook/webapp/resource/board.ts
* Add tab to table page to display lists containing the table
* Add button to datadoc displaying lists containing the doc
> feat: add reverse mapping for lists - list UI in table & datadocs pages

- package.json
- querybook/webapp/lib/query-result/detector.ts
- querybook/webapp/lib/query-result/transformer.tsx
- querybook/webapp/lib/utils/index.ts
Query results that is a valid url will automatically be transformed into <a> tags
> feat: add auto url transform to querybook

- package.json
- querybook/server/lib/query_analysis/templating.py
Before:
```
SELECT
*
FROM(
SELECT
'2019' AS Year,
Country,
Score
FROM
world_happiness_2019
ORDER BY
Rank
LIMIT
10
)
UNION
SELECT
*
FROM(
SELECT
'2018' AS Year,
Country,
Score
FROM
world_happiness_2018
ORDER BY
Rank
LIMIT
10
)
UNION
```
After
```
SELECT
*
FROM(
SELECT
'2019' AS Year,
Country,
Score
FROM
world_happiness_2019
ORDER BY
Rank
LIMIT
10
)
UNION
SELECT
*
```
> feat: strip white space when rendering templated queries

- querybook/server/lib/richtext.py
Noticed an issue, if the description is `"hello world"`, the code would think it is draftjs richtext even though it is not
> fix: draftjs backend parser

- querybook/webapp/components/QueryComposer/QueryComposer.tsx
Previously, query executions could be closed on the ad hoc page, but could not be reopened without re-executing the query. This change allows collapsing and expanding the query execution results, so it behaves similar to the sidebar.
> feat: Collapse and expand ad hoc query execution results

- package.json
- querybook/server/models/board.py
- querybook/webapp/components/Board/BoardItem.scss
- querybook/webapp/components/Board/BoardItem.tsx
- fixed board item order miscalculation
- Removed tooltip for buttons during drag and drop phase. The tooltip would make board item more bloated than what it actually looks like. In future, we should move to React based Tooltip solutions instead
- Removed duplicated CSS
> fix: list drag and drop

- querybook/server/datasources/datadoc.py
- querybook/webapp/components/DataDocTemplateButton/DataDocTemplateButton.tsx
- querybook/webapp/components/DataDocTemplateButton/DataDocTemplateCell.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/const/adhocQuery.ts
- querybook/webapp/redux/dataDoc/action.ts
- querybook/webapp/resource/dataDoc.ts
This PR is to add templating support for Adhoc query, like the datadocs. Changes include
- Add a dropdown menu to add template variables and preview template rendered query. 
- Also moved the "create datadoc" and "add udf" to the dropdown menu
- When creating datadoc from the adhoc query, it will pass the template variables over as well
> feat: Add templating support for Adhoc query

- package.json
- querybook/server/logic/elasticsearch.py
- querybook/webapp/components/Board/Board.tsx
- querybook/webapp/components/Board/BoardHeader.tsx
- querybook/webapp/components/Board/BoardItem.tsx
- querybook/webapp/components/BoardViewersBadge/BoardViewersBadge.tsx
- querybook/webapp/components/BoardViewersList/BoardViewersList.tsx
- querybook/webapp/components/EnvironmentAppRouter/EnvironmentModalSwitchRouter.tsx
- querybook/webapp/components/EnvironmentAppRouter/modalRoute/SearchRoute.tsx
- querybook/webapp/components/PublicBoardPage/PublicBoardPage.tsx
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/Search/SearchResultItem.tsx
- querybook/webapp/components/Search/SearchResultItemBoardItemAddButton.tsx
- querybook/webapp/context/BoardPage.ts
- querybook/webapp/redux/board/action.ts
- querybook/webapp/redux/board/reducer.ts
- querybook/webapp/redux/board/selector.ts
- querybook/webapp/redux/board/types.ts
- Fixed route computation that would take the previous non-modal route instead of the current non-modal route
- Fixed currentBoardId logic impacting ownership calculation
- Fixed board elasticsearch update, board['id'] needs to be passed in instead of board
> fix: various board related bugs

- package.json
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
Seeing below errors on adhoc queries. 
```
Failed to templatize query.
get_templated_query() missing 1 required positional argument: 'variables'
```
Cause:
In https://github.com/pinterest/querybook/pull/939, we added templating support for adhoc queries, while forgot to provide a default value when getting the `templatedVariables` from Redux store if there is no variables added, which will be undefined, while the render template API requires this argument.
> fix: adhoc template query

- querybook/webapp/__tests__/lib/sql-helper/sql-checker.test.ts
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/lib/sql-helper/sql-checker.ts
**Context**
Recently one of our P0 prod tables were accidentally dropped by a user through querybook. At best we would like to prevent such cases from happening. At a minimum we will like an option to warn the user that they are about to drop a critical prod table and they need to confirm before the statement execution goes through.
This PR will ask user to confirm before the query execution if it will drop any tables.
> feat: add confirmation before execution if the query drops any tables

- requirements/base.txt
Updating flask and sqlalchemy (and related packages) to the latest version.
Tested locally with default docker-compose MySQL 8
> chore: Upgrade flask and sqlalchemy versions

- querybook/webapp/__tests__/lib/sql-helper/sql-checker.test.ts
- querybook/webapp/__tests__/lib/sql-helper/sql-lexer.test.ts
- querybook/webapp/lib/sql-helper/sql-lexer.ts
getDroppedTables fails silently if the query is invalid because getStatementType would throw an exception when there is no keywords in the query. This should no longer be the case as it would return null instead
> fix: getStatementType vs invalid queries

- package.json
- querybook/server/lib/query_executor/clients/sqlalchemy.py
Instead of a list of string, the cursor.keys() now return RMKeyView. Apply list() to convert it back to a list of strings.
We definitely need to add some unit test in future to prevent things like this from happening
> Fix SQLAlchemy API change to return RMKeyView for columns

- querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx
This change adds a possibility to hide/show all columns in 'Hide columns' menu just using one checkbox.
> Feat: add 'All' button in the 'Hide columns' menu

- .github/workflows/pythontests.yml
- Dockerfile
- docs_website/docs/developer_guide/developer_setup.md
- package.json
- querybook/server/app/auth/utils.py
- querybook/server/app/db.py
- querybook/server/app/flask_app.py
- querybook/server/datasources_socketio/connect.py
- querybook/server/datasources_socketio/query_execution.py
- querybook/server/lib/query_executor/base_executor.py
- querybook/server/lib/query_executor/utils.py
- querybook/webapp/lib/data-doc/datadoc-socketio.ts
- querybook/webapp/lib/socketio-manager.ts
- querybook/webapp/redux/queryExecutions/action.ts
- requirements/base.txt
- requirements/engine/hive.txt
- requirements/engine/presto.txt
- requirements/shared/thrift.txt
- requirements/test.txt
- yarn.lock
Change list:
- Update to docker, python tests, etc
- Updated following packages: Werkzeug, Flask-Login, Redis, SocketIO, Celery, Greenlet, Pyhive, sasl, Pytest
- Updated SocketIO logic since it breaks after 3.10 update. I noticed once updated, I cannot reuse a namespace if it is disconnected before and I would need to create a new websocket connection. Now Querybook client would have at most 2 connections to server.
- Updated scopefunc for sqlalchemy db session due to werkzeug update
- Disconnect query execution would make it leave all the room
- Removed spread dict and use `|` operator instead
> chore: Upgrade to Python 3.10

- package.json
- querybook/server/app/datasource.py
- requirements/base.txt
with the recent update, it looks like flask.request.json would throw an error unless "Content-Type: application/json" is specified.
However, the axios library in the frontend requires data to be specified to add that header: https://github.com/axios/axios/issues/86
Updated flask to 2.2.0 and also make the backend check if the request is `is_json` before getting the parameters.
> fix: DELETE http does not work without params

- .github/workflows/pythontests.yml
- Dockerfile
- docs_website/docs/developer_guide/developer_setup.md
- package.json
- querybook/server/app/flask_app.py
Unfortunately, uWSGI is not Python 3.10 ready for websockets. 
We will need https://github.com/unbit/uwsgi/pull/2363 fix to be released.
Downgrade to 3.9 instead, tested both dev docker and prod docker
Also removed websocket logging
> fix: revert back to python 3.9

- package.json
- querybook/server/lib/query_executor/base_executor.py
- querybook/server/lib/query_executor/utils.py
- querybook/server/lib/richtext.py
- querybook/tests/test_lib/test_query_executor/test_utils.py
There is no need for stack trace of QueryExecutionError since they are thrown by Querybook for runtime verification and can be traced
> feat: dont show stack trace is exception is recognitizable

- querybook/webapp/components/DataDocChartCell/DataDocChart.tsx
- querybook/webapp/components/StatementResultTable/StatementResultTable.tsx
- querybook/webapp/components/StatementResultTable/common.ts
- querybook/webapp/components/StatementResultTable/useSortCell.ts
- querybook/webapp/lib/query-result/detector.ts
- querybook/webapp/lib/query-result/helper.ts
For sparse columns, the type checking werent working before since there will be a lot of null values affecting the quality of the result.  
Changes include:
- sampling and null filtering is done ahead of time before feeding into detectors
- transformer only runs on not null columns
- unified null checking code
> feat: Ignore null values when detecting types

- querybook/server/app/server.py
Previously, a trailing slash is required for initial server URL to work, now it is optional.
Tested with 
`/demo_environment/datadoc/10/ ` -> works
`/demo_environment/datadoc/10` -> works as well (this used to not work)
> fix: make trailing slash not required for catch all route

- querybook/webapp/ui/Markdown/Markdown.tsx
This feature allows executors to return and display warnings. Use cases include checking different table format and warn users who are referencing inefficient format. This PR does not include any specific warning, but it can be added like:
```
class SqlAlchemyCursor(CursorBaseClass):
_query: str = None
...
def run(self, query):
self._query = query
self._cursor = self._connection.execute(sqlalchemy.sql.text(query))
...
@property
def warning(self):
if self._query.__contains__("query_execution") is True:
return "This is a boring table"
else:
return None
```
```
SELECT * FROM querybook2.query_execution LIMIT 30;
SELECT * FROM querybook2.query_engine;
```
Running the sql above should give the warning like:
> feat: Allow executors to return warnings for query executions

- querybook/webapp/components/BoardExpandableList/BoardExpandableSection.scss
- querybook/webapp/components/DataTableNavigator/DataTableHoverContent.scss
- querybook/webapp/components/DataTableNavigator/DataTableHoverContent.tsx
- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.scss
- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx
> ui: fix overflow for long table name and .Title css

- docker-compose.yml
Pass utf8 as default charset into mysqld command (fixes #842)
> Pass utf8 as default charset into mysqld command (fixes #842)

- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.scss
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
We notice a possible overflow in "raw metastore info" section. In the case below, some of the column names is too long to fit in one line.
We did some css changes to break up the string if it is too long as
> fix: overflow in raw metastore info

- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/logic/metastore.py
Some systems may have the metastore as the source of truth for the table/column description, as well as the table schema. This change is to add the support of syncing table description from the metastore.
> feat: add support of syncing table/column description from metastore

- querybook/webapp/__tests__/lib/sql-helper/sql-lexer.test.ts
- querybook/webapp/__tests__/lib/sql-helper/sql-limiter.test.ts
- querybook/webapp/components/AppAdmin/AdminQueryEngine.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- querybook/webapp/const/adhocQuery.ts
- querybook/webapp/const/queryEngine.ts
- querybook/webapp/lib/sql-helper/sql-lexer.ts
- querybook/webapp/lib/sql-helper/sql-limiter.ts
- querybook/webapp/lib/sql-helper/sql-setting.ts
This change adds an optional Row Limit configuration to Query Engines.  When enabled, queries without a `LIMIT` clause will have one automatically added prior to execution, with the configured number of rows.  This is desirable to avoid inadvertently running unbounded queries on massive tables.
Users can manually disable this feature with a checkbox in the ad hoc editor, or by manually providing a `LIMIT` in their query.  This feature is not enabled for DataDocs.
Query detection support has been added for `LIMIT` and the SQL Standard `FETCH FIRST/NEXT` syntax, which covers a number of languages.  Additional parsing support would be needed to fully support other languages (e.g. SQL Server's `TOP`).
Additionally, the Trino language has been split from the Presto language to add support for …
> Automatically add a row limit to queries

- package.json
- querybook/server/datasources/metastore.py
This new API endpoint will sync a table (given schema name and table name) for a specific metastore (given metastore id), including creating, updating and deleting a table.
> feat: Add a new API of syncing a table from metastore

- querybook/webapp/lib/chart/chart-data-processing.ts
- querybook/webapp/lib/chart/chart-meta-processing.ts
Hi, I was asked to investigate an issue involving the `datalabels` plugin, as it was rendering `[object Object]` instead of any other value... after inspecting the integration code I realized that `chartData['labels']` is not always populated!
Then, I tried to play with the `datalabels.formatter` callback to see if was possible to get the missing label from there but it was not possible, after you save the chart options then `context.chart.data.labels` becomes an empty array.
It seems whenever the `chartjs-plugin-datalabels` receives an `undefined` value from any formatter then it renders `[object Object]` instead? &mdash; my workaround sets `charData['labels']` from the first-field on `dataRows` because I am not using `x_axis` (`xAxisIdx` is not zero!) as the same value for the labels, …
> Bugfix: scatter/bubble charts were losing their labels after save

- querybook/webapp/components/DataTableViewMini/ColumnIcon.tsx
- querybook/webapp/components/DataTableViewMini/TablePanelView.tsx
The column icon for partition keys doesn't look properly, here we
* center aligned it and make the icon size a bit smaller
* move the tooltip to right
**Before**
**After**
> fix: column icon css for partition keys

- package.json
- querybook/server/const/query_execution.py
- querybook/server/datasources/datadoc.py
- querybook/server/lib/query_executor/base_executor.py
- querybook/server/lib/query_executor/executor_factory.py
- querybook/server/tasks/run_datadoc.py
- querybook/server/tasks/run_query.py
- querybook/webapp/const/queryExecution.ts
Add query execution type as enum, and pass it down to the executor client
* adhoc
* scheduled
with that, we can pass the scheduled flag to the Presto client, something like 
```
connection = presto.connect(
...
session_props={'presto_scheduled_query': 'true'}, # when execution type is scheduled
)
```
> feat: pass execution type to executor client

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
When updating a query with lint error to use template variables, the error still remains, while it's supposed to disappear for templating queries.
> fix: lint error doesn't disappear when switching to templating query

- docs_website/docs/integrations/customize_html.md
- package.json
- querybook/config/datadoc.yaml
- querybook/webapp/__tests__/lib/sql-helper/sql-lexer.test.ts
- querybook/webapp/__tests__/lib/sql-helper/sql-limiter.test.ts
- querybook/webapp/components/AppAdmin/AdminQueryEngine.tsx
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/components/QueryComposer/RunQuery.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.scss
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- querybook/webapp/const/adhocQuery.ts
- querybook/webapp/const/datadoc.ts
- querybook/webapp/lib/sql-helper/sql-lexer.ts
- querybook/webapp/lib/sql-helper/sql-limiter.ts
- querybook/webapp/types.d.ts
- The feature flag is now a boolean instead of int
- You can set limit for query cells too (refactored code, so the composer and cell use the same function to transform query)
- The query limit is now a dynamic scaling system with max 10^6 and default 10^3. This value can also be configured with plugins. Also updated the plugin documentation
- Refactored code for detecting limit in queries
- For queries that are limited, add a warning to let the users know
> feat: improved query limit

- package.json
- querybook/server/datasources/metastore.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/lib/table_upload/exporter/base_exporter.py
- querybook/server/tasks/log_query_per_table.py
For syncing a table with metastore, the caller may not know if it's an updating or deleting, it should be the sync function's responsibility to keep it sync with metastore, whether it's creating, updating or deleting.
Also the `get_all_table_names_in_schema` method used for checking table existence is actually not very efficient for those schema with a huge amount of tables, it could cost 1 to 2 seconds. So this new function will use `get_table_and_columns` to check, and its response will also be used for creating/updating the table as it will be needed anyway if it's not deleting.
> feat: Add a new function to sync table with metastore

- docs_website/docs/integrations/customize_html.md
- package.json
- querybook/webapp/components/ConfirmationManager/ConfirmationManager.tsx
- querybook/webapp/components/ConfirmationManager/ConfirmationMessage.tsx
- querybook/webapp/components/QueryComposer/RunQuery.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- querybook/webapp/lib/sql-helper/sql-lexer.ts
- querybook/webapp/lib/sql-helper/sql-limiter.ts
- querybook/webapp/types.d.ts
Added a new flag ALLOW_UNLIMITED_QUERY which is turned on by default. This means there is an new option "none" to skip the limit query postprocessing
If user did pick none and ran a query without limit, they are shown this warning modal every time:
> feat: allow user to bypass LIMIT

- package.json
- querybook/server/datasources/metastore.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- querybook/webapp/hooks/ui/useContextMenu.ts
- querybook/webapp/hooks/useMounted.ts
- querybook/webapp/redux/dataSources/action.ts
- querybook/webapp/redux/dataSources/reducer.ts
- querybook/webapp/redux/dataSources/types.ts
- querybook/webapp/resource/table.ts
- querybook/webapp/ui/ErrorPage/ErrorPage.scss
When clicking "Refresh from metastore", if the table gets deleted, we'll show an empty 404 page.
Also the previous error page of table not found is not rendered properly.
**Before**
**After**
> feat: show 404 page when table gets deleted

- querybook/server/lib/metastore/base_metastore_loader.py
for the metastore `sync_table`, it also needs to go through the acl check. For tables not in the allow list or in the deny list, we'll skip the sync.
> fix: add acl check for metastore table sync

- querybook/server/datasources/metastore.py
raise rate limit for the metastore sync api to 500 per min
> fix: raise rate limit for the sync api

- package.json
- querybook/server/datasources/datadoc.py
- querybook/server/logic/schedule.py
- querybook/webapp/components/DataDocSchedule/DataDocScheduleForm.tsx
- querybook/webapp/const/schedule.ts
Today when the datadoc gets transferred, the datadoc's schedule wont be transferred. This PR is to fix it.
Also adding a message in the schedule form to tell people that the datadoc's owner will be sent for notification and it is also the one who will be running the query.
> fix: transfer schedule's ownership along with datadoc's ownership

- querybook/server/lib/metastore/base_metastore_loader.py
It's supposed to return none for invalid tables, while it wrongly returns none for valid table
> fix: table validation for sync_table

- querybook/server/lib/utils/json.py
this provides a more generic solution when serializing SQLAlchemy rows, see https://github.com/pinterest/querybook/pull/1009 for the bug it fixes
> fix: automatic serialize sqlalchemy Row

- package.json
- querybook/server/logic/elasticsearch.py
- querybook/server/logic/schedule.py
- querybook/server/tasks/all_tasks.py
- querybook/server/tasks/disable_scheduled_docs.py
- querybook/tests/test_lib/test_elasticsearch/test_elasticsearch.py
- querybook/webapp/components/DataDocViewersBadge/DataDocViewersBadge.tsx
- querybook/webapp/components/UserBadge/UserAvatar.scss
- querybook/webapp/components/UserBadge/UserAvatar.tsx
- querybook/webapp/components/UserBadge/UserBadge.tsx
- querybook/webapp/const/user.ts
Disabled users are now searchable in user search.
They will also look different in UI, with grayed out icon and `(deactivated)` added to their name:
Also added a task to disable scheduled docs if the owner is deleted, this task is optional
> feat: show deactivated user with different ui

- package.json
- querybook/server/lib/query_analysis/validation/all_validators.py
the fix is needed as otherwise this would make Pyhive a required dependency for Querybook
> fix: Make Presto Explain Validator optional install

- querybook/webapp/lib/query-result/transformer.tsx
From user's feedback, by enabling the json formatting by default causes inconvenience for them. 
Here we'd like to disable the auto formatting, but user can transform the column as needed by themselves.
> fix: disable json formatting by default

- querybook/server/logic/schedule.py
with operator `|=`,  the id of `task_schedule.kwargs` remains the same, in which case `SQLAlchemy` will treat it as not mutated.
> fix: schedule owner not update

- querybook/webapp/lib/sql-helper/sql-autocompleter.ts
for the sql keyword auto completion, when the user already has type the exact keyword, it will still show the hint and it will be selected when user types "enter". Here we're not going to show the hint for this case.
> fix: disable autocomplete for exact keyword matches

- querybook/webapp/components/QueryEditor/QueryEditor.scss
The autocomplete feature in the Query editor currently has a z-index of 30, whereas modals are 300.  This causes issues on the Snippet editor:
This bumps the z-index up to 400 to fix:
> fix: Increase CodeMirror hint z-index above modals

- querybook/server/lib/query_analysis/transpilation/base_query_transpiler.py
- querybook/server/lib/query_analysis/transpilation/transpilers/sqlglot_transpiler.py
- querybook/webapp/components/TranspileQueryModal/TranspileQueryModal.tsx
- querybook/webapp/const/queryEngine.ts
- querybook/webapp/resource/queryExecution.ts
Now when transpiled with SQLGlot, we would also format the query previously for better comparison view:
Original query: select MAP(ARRAY[ARRAY['foo'], ARRAY['bar']], ARRAY[1, 2]) limit 1000;
> feat: add formatted transpile view

- querybook/webapp/components/QueryExecution/ExecutedQueryCell.tsx
**Issue**: 
the scroll bar in the "show query" window keeps resetting to its top position when the query is actively running.
**Cause**: 
Although we used `useMemo` for `ThemedCodeHighlightWithMark`'s prop `highlightRanges`, but it depends on `highlightRange`,  which will be recreated every time when passed from its parent, which leads to re-render
```            <ExecutedQueryCell
queryExecution={queryExecution}
highlightRange={
statementExecution && {
from: statementExecution.statement_range_start,
to: statementExecution.statement_range_end,
}
}
changeCellContext={changeCellContext}
/>
```
Another option tried is to memoize this `highlightRange` on its parent component
```
const highlightRange = useMemo(()=>statementExecution && {
from: statementExecution.statement_range_start,
to: …
```
> fix: ExecutedQueryCell auto scropll to top during execution

- docs_website/docs/setup_guide/prod_setup.md
since it is not obvious to admins on how to start the db initially
> docs: add instruction on init_db

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
On the `Execs` tab, the query editor starts with empty, only shows query after clicking it. Forgot to move this over when refactoring from class to functional component. Added it back here.
> fix: codemirror starts with a wrong height

- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/redux/search/reducer.ts
- querybook/webapp/redux/search/types.ts
When switching the search type tab, we'd like to keep the search string the same, to make it the behavior consistent with popular search engines.
Also updated some the date filters for the table and datadoc tab as `Created At` to make it less confused.
> ui: keep the search string when switching the search type

- querybook/webapp/components/QueryComposer/QueryComposer.tsx
Fixes issues with the Transpile Query submenu appearing under the sidebar.
> fix: QueryComposer additional buttons nested right

- querybook/webapp/components/DataDocTemplateButton/DataDocTemplateVarForm.tsx
- querybook/webapp/components/DataDocTemplateButton/helpers.ts
**Issue**
1. when changing the var type from string to number or vice versa, the type will actually not get updated after refreshing the page.
2. for number type with really big values, it will be rounded
**Cause**
1. when only changing the `valueType`, but not update the value field, the value field will not get re-rendered so that the value will not be re-evaluated. So when clicking save, it will still have the old type.
2. The maximum number Javascript supports is `Number.MAX_SAFE_INTEGER` (2^53-1 )
**Fix**
* evaluate the value according to the type when saving
* update the `Yup` shcema validation for numbers bigger than `Number.MAX_SAFE_INTEGER`  to ask user to use string type instead
* use `SimpleField` with `type={'input'}` for both `string` and `number` type. 
* The reason of this …
> fix: template variable type change and big numbers

- docs_website/docs/integrations/add_dag_exporter.md
- querybook/server/datasources/dag_exporter.py
- querybook/server/lib/dag_exporter/all_dag_exporter.py
- querybook/server/lib/dag_exporter/base_dag_exporter.py
- querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py
- querybook/server/logic/admin.py
- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.scss
- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporter.tsx
- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterListItem.tsx
- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterSettings.tsx
- querybook/webapp/components/DataDocRightSidebar/DataDocRightSidebar.tsx
- querybook/webapp/const/datadoc.ts
- querybook/webapp/context/DataDocDAGExporter.ts
- querybook/webapp/hooks/dag/useExporterDAG.ts
- querybook/webapp/hooks/dag/useExporterSettings.ts
- querybook/webapp/hooks/dag/useSavedDAG.ts
- querybook/webapp/redux/dataDoc/action.ts
- querybook/webapp/redux/dataDoc/reducer.ts
- querybook/webapp/redux/dataDoc/types.ts
- querybook/webapp/resource/dataDoc.ts
- querybook/webapp/ui/FlowGraph/QueryCellNode.scss
- querybook/webapp/ui/FlowGraph/QueryCellNode.tsx
Add query engine validation on both client and server side
- display supported engine list on the settings panel
- add warning icons for cells with unsupported engines
- return error if there is any engine unsupported when exporting
left bar with query cells
query cell node
query engines
export result error
> feat: add query engine validation for dag exporter

- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterSettings.tsx
**Issue**
dag exporter will return all supported engine ids, while the frontend only know the engines of the current env, which fails to get engine name not in the env.
**Fix**
we'll only show the supported engine list which belongs to the current env
> fix: only show supported query engines in the current env for dag exporter

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/hooks/queryEditor/useAutoComplete.ts
- querybook/webapp/hooks/queryEditor/useCodeAnalysis.ts
- querybook/webapp/hooks/queryEditor/useLint.ts
instead of useEffect to compute async annotations, made them using hooks to react to changes.
This fixes the bug of table linting not working when the query editor is mounted
> fix: refactored useLint pipeline to be more hooks based

- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx
- querybook/webapp/components/DataTableNavigator/SchemaTableView/SchemaTableItem.tsx
- querybook/webapp/const/search.ts
- querybook/webapp/redux/dataTableSearch/action.ts
- querybook/webapp/redux/dataTableSearch/reducer.ts
- querybook/webapp/redux/dataTableSearch/types.ts
- querybook/webapp/ui/OrderByButton/OrderByButton.tsx
Since the table search currently doesn't have a sort order, this PR is to have the search result list in ascending order using schema and name.
Note: Also fixed the `importance_score` sorting feature on the schema table sort
> fix: Add sort_key and sort_order to table search

- querybook/server/datasources/metastore.py
- querybook/server/logic/metastore.py
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/Search/SearchSchemaSelect.tsx
- querybook/webapp/resource/search.ts
This feature allows DataDocs to be filtered by a schema. 
A user can select schema using multi select.
A user can select more than one schema.
A user can remove any selected schema.
> Feat: add schema filtering for table search

- querybook/server/lib/scheduled_datadoc/notification.py
1. `notification_params` wrongly formatted as a tuple
2. incorrect parameter name `notify_name`, supposed to be `notifier_name`
> fix: schedule notification exception

- querybook/server/tasks/run_datadoc.py
If a DataDoc has a templating error (e.g. non-existent variable), scheduled runs will fail silently without creating run history or sending notifications, making it hard to find and fix the issue. 
This PR patches this by creating the `TaskRunRecord` before attempting to render any queries, then updating it with an error message if any rendering exceptions occur.
> fix: Ensure DataDoc runs get tracked even if template rendering fails

- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.scss
- querybook/webapp/components/DataTableViewMini/TablePanelView.tsx
We use lots of long struct types, which cause some display problems.  This PR includes two fixes: 
1. In the table sidebar, long types are truncated, since users can click to view the full type in the ColumnPanelView:
2. In the Column tab of the table view, long types are wrapped so the entire contents can be veiwed:
> fix: Wrap or truncate long column types

- querybook/server/app/auth/__init__.py
- querybook/server/app/datasource.py
- querybook/server/datasources/user.py
- querybook/server/lib/event_logger/__init__.py
some api endpoints may have sensitive like password. here we'll disable the logging for all the admin api and login/signup endpoints
> fix: disable some api reqests from event logging

- querybook/webapp/components/Announcements/Announcements.tsx
- querybook/webapp/hooks/useInterval.ts
Found there are a lot of api calls of `/announcement/`, which is about more than 1/3 of total api calls. Here we change it to only call it when the tab is active.
> fix: load announcements only if the tab is active

- querybook/notification_templates/schedule_disabled_notification.md
- querybook/server/tasks/disable_scheduled_docs.py
3 policies:
- disable if user is deactived
- disable if run failed for past N times
- disable if no one has viewed the doc for past N days
Also has notification to owner once its disabled
> feat: add helper task to auto disable unused workflows

- package.json
- querybook/webapp/components/DataDocDAGExporter/DataDocDAGExporterGraph.tsx
- querybook/webapp/components/DataTableViewLineage/DataTableViewLineage.tsx
- querybook/webapp/const/datadoc.ts
- querybook/webapp/hooks/dag/useExporterDAG.ts
- querybook/webapp/hooks/dag/useSavedDAG.ts
- querybook/webapp/redux/dataDoc/action.ts
- querybook/webapp/resource/dataDoc.ts
- querybook/webapp/ui/FlowGraph/FlowGraph.tsx
- querybook/webapp/ui/FlowGraph/GraphControls.tsx
- querybook/webapp/ui/FlowGraph/LineageNode.tsx
- querybook/webapp/ui/FlowGraph/QueryCellNode.tsx
- querybook/webapp/ui/FlowGraph/RemovableEdge.tsx
- querybook/webapp/ui/FlowGraph/helpers.ts
- yarn.lock
**Issue**
When deleting a query cell by clicking the "X" hover icon in DAG exporter, the edge connecting to the node are not actually deleted. When the node is added back to the graph, the edge is still there.
**Fix**
The latest react-flow v11.3 provide a util function of `deleteElements` to help deleting an element, which will have the correct behavior. Here we're upgrading react-flow to v11 and use this function to do the node deleting.
> fix: remove the edge when the node is deleted in dag exporter

- package.json
This is a dummy change to make a new version release for the CVE fix 
See changes here: https://github.com/pinterest/querybook/commit/88a7f10495bf5ed1a556ade51a2f2794e403c063
> chore: bump version to 3.14.2 for CVE

- .pre-commit-config.yaml
- package.json
- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx
- querybook/webapp/components/DataTableNavigator/SchemaTableView/SchemaTableItem.tsx
- querybook/webapp/const/metastore.ts
- querybook/webapp/redux/dataTableSearch/action.ts
- querybook/webapp/redux/dataTableSearch/const.ts
- querybook/webapp/redux/dataTableSearch/reducer.ts
several users reported that the search results are getting less relevant, this is because the search is defaulted to sort by alphabetical instead of relevancy.
- renamed importance score to relevance 
- For search, changed the default ordering to be by relevance
> fix: sidebar search should use relevance instead of alphabetical

- querybook/server/lib/elasticsearch/search_table.py
- querybook/webapp/redux/dataTableSearch/action.ts
The previous tuning of https://github.com/pinterest/querybook/pull/631/files will boost score for all phrase match, not limited to exact match. e.g.
query: `default.hello_world`
candidate 1: `default.hello_world`
candidate 2: `default.hello_world_v2`
both candidate 1 and 2 will have the phrase match, while candidate 1 is the exact match. 
This change will boost another score for the exact match of candidate 1.
> fix: boost table score for exact match when searching table

- querybook/server/lib/elasticsearch/search_table.py
If the search keywords contains table schema, boost 100, boost 10 if not.
> Tune exact match boost score of table search

- querybook/server/lib/query_analysis/templating.py
- querybook/server/tasks/run_datadoc.py
**Issue**
A user reported that one of their scheduled doc failed to run with status stuck on `RUNNING`, while manual run each query cell succeeds. (manual run the schedule also fails). 
**Findings**
* Error message got from the docker container: 
```[2022-12-13 18:44:36,616: ERROR/ForkPoolWorker-210079] Task run_data_doc_216961[532b190e-f6c3-4710-8a84- bc6f2701f904] raised unexpected: DetachedInstanceError('Instance <DataCell at 0x7f040851f250> is not bound to a Session; attribute refresh operation cannot proceed')```
* We dont see similar failure from other scheduled data docs
* The difference from the user's scheduled doc  is one of the query has template function `latest_partition`
* More investigation shows that, the issue only happens when 
* one of the query has template function …
> fix: scheduled docs with latest_partition fail to run

- package.json
- querybook/webapp/lib/query-result/transformer.tsx
**Issue**
The json column transformer somehow didn't work with error 
```
Uncaught TypeError: e.hasOwnProperty is not a function
at vendors-node_modules_lodash_sampleSize_js-node_modules_react-json-view_dist_main_js.1fa9e63d206dc9b137e1.js:209:107637
at Array.forEach (<anonymous>)
at a.renderObjectContents (vendors-node_modules_lodash_sampleSize_js-node_modules_react-json-view_dist_main_js.1fa9e63d206dc9b137e1.js:209:107544)
```
**Cause**
The parsed json object doesn't has functions like `hasOwnProperty` from the `Object` prototype.
**Fix**
As a workaround, we'll use object spread to copy the parsed json over to a plain Javascript object.
> fix: hasOwnProperty is not a function issue from json-big

- package.json
- querybook/server/app/auth/__init__.py
- querybook/server/lib/event_logger/__init__.py
- querybook/webapp/components/SessionExpirationNotice/SessionExpirationNotice.tsx
when user logs out, allow auth module to provide additional callback before actually logging them out via flask_login
also fixed a bug where current_user.id is used for unauth endpoints
> feat: add logout event hook

- querybook/webapp/components/DataDocSchemaNavigator/DataDocSchemaNavigator.scss
- querybook/webapp/components/DataDocSchemaNavigator/DataDocSchemaNavigator.tsx
- querybook/webapp/hooks/table/useExactMatchTableId.ts
If you enter the table name exactly, the table would auto show up in the bottom bar
> feat: Make exact table search result auto show up

- package.json
- querybook/webapp/components/DataDoc/DataDoc.tsx
- querybook/webapp/components/DataDocCell/DataDocCell.tsx
- querybook/webapp/components/DataDocChartCell/DataDocChartCell.tsx
- querybook/webapp/components/DataDocLeftSidebar/DataDocLeftSidebar.tsx
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/DataDocTextCell/DataDocTextCell.tsx
- querybook/webapp/const/keyMap.ts
- querybook/webapp/context/DataDoc.ts
- querybook/webapp/lib/data-doc/data-doc-utils.ts
- Added Alt+T to toggle ToC within a DataDoc
- Changed copy/paste/delete shortcut from `Alt-Shift` to just Alt
> feat: Add shortcut for toggle ToC, update datadoc short cuts

- package.json
- querybook/webapp/const/dataDocChart.ts
- querybook/webapp/lib/chart/chart-data-processing.ts
- querybook/webapp/lib/chart/chart-meta-processing.ts
- querybook/webapp/lib/chart/chart-utils.ts
added a new axis type "date" to handle charting that is purely date. Now "2022-12-20" would be detected as date axis, while "2019-09-07T-15:50+00" would be parsed as datetime
> fix: Chart date axis bug

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/hooks/queryEditor/useAutoComplete.ts
- querybook/webapp/lib/sql-helper/sql-autocompleter.ts
- querybook/webapp/lib/sql-helper/sql-setting.ts
If a column is like "foo/bar" then querybook would auto add quotes around the column names, similarly for tables.
For Presto
For MySQL
also 2 bug fixes:
- If column name has upper case, still match prefix
- make sure getSQLHint always goes to the latest language type
> feat: auto add quotes for table/columns

- querybook/migrations/versions/63bde0162416_update_event_type_in_event_log_table.py
Forgot to migrate the db in PR #1110 to add the new enum value to the `event_type` column
> fix: update event_log table schema

- querybook/webapp/components/DataDoc/DataDoc.tsx
- querybook/webapp/components/DataDocNavigator/DataDocGridItem.scss
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- querybook/webapp/components/DataTableViewQueryExample/DataTableViewQueryExamples.scss
- querybook/webapp/components/DataTableViewQueryExample/DataTableViewQueryExamples.tsx
- querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.tsx
- querybook/webapp/const/chartColors.ts
- querybook/webapp/hooks/chart/useChartSource.ts
- querybook/webapp/hooks/useLocalStoreState.ts
- querybook/webapp/lib/local-store/const.ts
- querybook/webapp/redux/queryExecutions/action.ts
- querybook/webapp/redux/queryExecutions/reducer.ts
- querybook/webapp/redux/queryExecutions/types.ts
- querybook/webapp/ui/EditableTextField/EditableTextField.tsx
- querybook/webapp/ui/Link/ListLink.tsx
- querybook/webapp/ui/RichTextEditor/RichTextEditor.tsx
Features:
- added placeholder for table description
- added cell title for query examples
- querybook would now memoize the sidebar being selected
Fixes:
- Adding a new query cell would now trigger auto focus
- hovering over datadocs in favorite section would not cause the row to expand
- the x buton for untitled doc in favorite section would be right aligned
- renamed the second blue in chart series color to "picton blue" to avoid duplicate naming
> feat: a bunch of small ui fixes and improvements

- package.json
- querybook/server/const/event_log.py
- querybook/server/datasources/__init__.py
- querybook/server/datasources/event_log.py
- querybook/server/lib/event_logger/__init__.py
- querybook/server/lib/event_logger/base_event_logger.py
- querybook/server/lib/event_logger/loggers/console_event_logger.py
- querybook/server/lib/event_logger/loggers/db_event_logger.py
- querybook/server/lib/event_logger/loggers/null_event_logger.py
- querybook/webapp/components/ChangeLog/ChangeLog.tsx
- querybook/webapp/components/EnvironmentAppSidebar/EntitySidebar.tsx
- querybook/webapp/components/InfoMenuButton/InfoMenuButton.tsx
- querybook/webapp/components/Landing/Landing.tsx
- querybook/webapp/components/QueryEngineStatusButton/QueryEngineStatusButton.tsx
- querybook/webapp/components/Search/SearchContainer.tsx
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/Search/SearchResultItem.tsx
- querybook/webapp/components/UserMenu/UserMenu.tsx
- querybook/webapp/const/analytics.ts
- querybook/webapp/hooks/useTrackView.ts
- querybook/webapp/lib/analytics.ts
- querybook/webapp/lib/batch/batch-manager.ts
- querybook/webapp/resource/analytics.ts
Add frontend instrument logging.
> feat: add frontend context logging

- querybook/webapp/components/DataDocScheduleList/DataDocScheduleItem.tsx
This PR provides some visual cues for disabled schedules in the Schedules list: 
- Shows `Next Run: Disabled` instead of the would-be timestamp (if it was enabled)
- The DataDoc name heading is lightened
> fix: Add disabled indicators to Schedules list

- package.json
- querybook/webapp/__tests__/lib/utils/complex-types.test.ts
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.scss
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCardNestedType.tsx
- querybook/webapp/components/DataTableViewMini/ColumnPanelView.tsx
- querybook/webapp/components/DataTableViewMini/TablePanelView.tsx
- querybook/webapp/lib/utils/complex-types.ts
- querybook/webapp/stylesheets/_utilities.scss
This is an alternate version of #1072, replacing the JSON viewer with a more natural-looking nested type drilldown.  I've also addressed some issues with the original version.
Compared to #1072, the parser is more consistent and does a better job of handling certain types than before.  To support the nesting, it always creates nodes with optional children.  Now `array<>` and `uniontype<>` types will create placeholder `<element>` nodes underneath them, and `map<>` types create placeholder `<key>` and `<value>` nodes.
Complex type parsing is case-insensitive (e.g. struct vs STRUCT) but otherwise case is preserved.
There are three main features:
1. Columns with complex types can be expanded directly in the TablePanelView to see a nested representation (initially collapsed).
2. The type …
> feat: Visualize complex Hive column types v2

- docker-compose.yml
Introduced below two lines of duplicate mount in #1117 
`- $PWD/docs_website/static/changelog:/opt/querybook/querybook/static/changelog`
`- /opt/querybook/querybook/static/changelog/`
removing the 2nd one.
> fix: remove duplicate volume mount

- querybook/webapp/__tests__/ui/__snapshots__/EditableTextField.test.js.snap
- querybook/webapp/components/DataDocTextCell/DataDocTextCell.tsx
- querybook/webapp/components/SearchAndReplace/DraftJsSearchHighlighter.tsx
- querybook/webapp/hooks/useStateWithRef.ts
- querybook/webapp/ui/EditableTextField/EditableTextField.tsx
- querybook/webapp/ui/RichTextEditor/RichTextEditor.tsx
- querybook/webapp/ui/RichTextEditorToolBar/RichTextEditorToolBar.tsx
- RichTextEditor and RichTextEditorToolbar are now in hooks
- No other logic change except componentDidCatch was removed
> chore: update richtext editor to hooks

- querybook/webapp/lib/query-result/transformer.tsx
This is the same issue which #1103 tried to fix, while it only fixed the top level, but not nested objects.  Here is another workaround by stringify and parse it again with builtin JSON module.
> fix: json-bigint hasOwnProperty undefined issue

- querybook/server/datasources/event_log.py
- querybook/webapp/resource/analytics.ts
The `/event_log/` api will be blocked by chrome adblocker extension. In the blocking log, it shows the `/event_log/*` will be blocked, here we change the path name to `/context_log/`
> fix: update /event_log api path

- package.json
- yarn.lock
The react-table package version upgrade in #1123 will cause exception when there are empty rows in the execution result. here we're reverting the version change
> fix: react-table version

- querybook/webapp/__tests__/ui/__snapshots__/Table.test.js.snap
- querybook/webapp/lib/utils/error.ts
axios error constructor is not using Error, changed it for just object check
> fix: axios error display

- querybook/server/lib/query_analysis/validation/validators/presto_explain_validator.py
timeout would cause the whole web process to fail. If you want to configure timeout, you would need to pass in the timeout parameter during the engine connection separately
> fix: remove timeout for presto explain

- package.json
- querybook/server/const/metastore.py
- querybook/server/datasources/metastore.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/models/admin.py
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableViewColumn.tsx
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- querybook/webapp/const/metastore.ts
- querybook/webapp/redux/dataSources/selector.ts
- querybook/webapp/resource/table.ts
- querybook/webapp/ui/EditableTextField/EditableTextField.tsx
As we may sync more metadata types from metastore, like owners, tags, here we are adding a config for the metastore loader so that we can manage whether the metadata should be read-only or written back to metastore.
By default, it will keep the current behavior, which is only writing into querybook db.
> feat: add metastore loader config

- querybook/server/logic/schedule.py
- querybook/webapp/components/AppAdmin/components/EnvironmentSelection/EnvironmentSelection.tsx
- querybook/webapp/components/DataDocScheduleList/DataDocBoardsSelect.tsx
- querybook/webapp/components/DataDocScheduleList/DataDocSchedsFilters.tsx
- querybook/webapp/components/DataDocScheduleList/DataDocScheduleList.tsx
- querybook/webapp/const/options.tsx
- querybook/webapp/const/schedFiltersType.ts
- querybook/webapp/redux/scheduledDataDoc/action.ts
- querybook/webapp/redux/scheduledDataDoc/reducer.ts
- querybook/webapp/redux/scheduledDataDoc/types.ts
- querybook/webapp/resource/dataDoc.ts
- querybook/webapp/ui/SimpleReactSelect/SimpleReactSelect.tsx
This commit adds a bunch of filters for Scheds page.
There are two filters - filter by status and public user lists.
Filter by status has three options: All (default), Enabled and Disabled. A user can choose only one option.
Filter by user lists contains all custom-created lists and a user can select any of them. A user also can choose more than one list.
> Feat: add enable and list filters for Scheds

- querybook/webapp/components/DataDocRightSidebar/DeleteDataDocButton.tsx
This fixes an issue where deleting a DataDoc in a non-default environment causes the UI to jump to the default environment instead of remaining in the current environment. The issue seems to be related to QB reloading after attempting to navigate to '{currentEnv.name}/datadoc' after deleting a datadoc. The change included in this PR avoids the reload while also refreshing the page to be able to see that the datadoc was deleted.
> fix: stay on current env after deleting doc

- querybook/webapp/lib/datasource.ts
- querybook/webapp/lib/utils/error.ts
- querybook/webapp/resource/queryExecution.ts
* add the timeout option for axios request
* set timeout as 5s for syntax validate api requests
* display AxiosError.message instead of the whole object
> add axios request timeout option

- querybook/webapp/components/QueryViewNavigator/QueryViewNavigator.tsx
> chore: Move QueryViewNavigator to hooks

- querybook/webapp/components/QueryRunButton/QueryRunButton.scss
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- querybook/webapp/ui/SearchBar/SearchBar.scss
- querybook/webapp/ui/SearchBar/SearchBar.tsx
Adds a search bar to the list of query engines, scrolling functionality, and a button to clear keywords from the search bar.
> feat: query engine search scroll

- querybook/webapp/components/DataDocStatementExecution/StatementResult.scss
- querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx
- querybook/webapp/ui/SearchBar/SearchBar.scss
- querybook/webapp/ui/SearchBar/SearchBar.tsx
Adds a search bar to the hide columns popup to allow searching table column names with a keyword. Can select or hide all columns found with keyword.
> feat: add search box to hide columns popup

- package.json
- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/lib/sql-helper/sql-formatter.ts
user reported sql-formatter is throwing errors when formatting statements with `BETWEEN`. See https://github.com/sql-formatter-org/sql-formatter/issues/534 for details
In this PR, I added try/catch when calling format to make it safer. Also refactored the code to break it down into smaller functions
> fix: add safe suppress to sqlformat error

- querybook/webapp/ui/RichTextEditor/RichTextEditor.tsx
**Issue**
In readonly mode, when user clicks a text cell, querybook will crash. 
**Cause**
`toolBarRef.current` is null in readonly mode.
> fix: clicking a readonly text cell causes querybook crash

- querybook/webapp/components/DataDocScheduleList/DataDocScheduleItem.tsx
PR #1122 introduced a bug with the Scheduled DataDoc Only toggle.  Unchecking this option would cause a crash if DataDocs without a schedule are returned.
> fix: Fix Scheduled DataDocs Only toggle

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/lib/sql-helper/sql-formatter.ts
sql-formatter is not working properly.
and also the behavior is not consistent between adhoc and datadoc
**cause**: 
https://github.com/pinterest/querybook/pull/1141/files#diff-f96c7f939d2f6190281fe1288630f6ce6e7efec269cd71a04a16a6379686e38fR185
**fix**
* make the silent option to be default false for both adhoc and datadoc
* format either fail or succeed on the whole query, not per statement
> fix: sql-formatter

- querybook/server/lib/event_logger/__init__.py
worker can't get current user. here we're changing the uid to be optional, which will be default to 0.
> fix: event logger when current user is None

- querybook/server/lib/query_analysis/templating.py
Queries contain a number template variable with value 0 can't be rendered properly. The value will become empty.
> fix: number type variable with value 0

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/hooks/queryEditor/useLint.ts
Show message when lint api failed instead of showing lint passed
> feat: add message when linter failed to run

- querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.scss
- querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.tsx
This is just a linear interpolation on how long the query would finish
> feat: add estimated time for query execution

- querybook/webapp/components/TableUploader/useQueryEnginesForUpload.ts
This fixes an issue where having a query engine with a missing or deleted metastore causes the Table Upload UI to crash on the "Table Spec" section.
> fix: filter null store values

- querybook/server/datasources/datadoc.py
- querybook/webapp/components/DataDocRightSidebar/DataDocRunAllButton.tsx
- querybook/webapp/components/DataDocRightSidebar/DataDocRunAllButtonConfirm.tsx
- querybook/webapp/resource/dataDoc.ts
Added a toggle to the run all confirmation page so that users can choose whether they want a notification to be sent upon run completion. By default, the notification and toggle will be enabled to match previous behavior of Querybook where a notification will always be sent to the user upon run completion. The type of notification sent is still based on "notification preference" in user settings.
> feat: toggle run all notifications

- querybook/server/datasources/query_execution.py
previously, we would just send abort signal to the execution. But if the query is not running in celery, then nothing would be done. This PR adds more checks on the API side to update query status if the execution itself is gone
> feat: Add ability to cancel dead queries

- querybook/server/const/metastore.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py
- querybook/server/lib/metastore/loaders/hive_metastore_loader.py
- querybook/server/lib/metastore/loaders/mysql_metastore_loader.py
- querybook/server/lib/metastore/loaders/sqlalchemy_metastore_loader.py
- querybook/server/lib/metastore/loaders/thrifthive_metastore_loader.py
- querybook/server/lib/metastore/metastore_data_types.py
- querybook/server/logic/tag.py
- querybook/tests/test_lib/test_metastore/test_loaders/test_glue_data_catalog_loader.py
- querybook/webapp/components/DataTableTags/DataTableTags.scss
- querybook/webapp/components/DataTableTags/DataTableTags.tsx
- querybook/webapp/components/DataTableTags/TableTagConfigModal.tsx
- querybook/webapp/components/DataTableTags/TableTagGroupSelect.tsx
- querybook/webapp/components/DataTableView/DataTableHeader.scss
- querybook/webapp/components/DataTableView/DataTableHeader.tsx
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/components/Search/TableSelect.tsx
- querybook/webapp/const/tag.ts
- querybook/webapp/stylesheets/_utilities.scss
- querybook/webapp/ui/Tag/HoverIconTag.tsx
- querybook/webapp/ui/Tag/Tag.scss
- querybook/webapp/ui/Tag/Tag.tsx
Allow loading tags from metastore
- By default, it will not load tags from metastore. 
- To enable it
- Update metastore loader's `loader_config` to have `MetadataType.TAG` not equal to ` MetadataMode.WRITE_LOCAL`. 
- Update metastore loader's `get_table_and_columns` function to return tags as `table.tags`
- If enabled loading tags from metastore, tags can't be added or updated through Querybook UI.
- All the tags synced from metastore will have `tag.admin = True`
- Added a new meta field `meta.type` to indicate a tag type. If a tag has a type, it will be rendered along with the tag name as a tag group. see below screenshot as an example
> feat: load tag from metastore

- querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.scss
- querybook/webapp/components/DataDocStatementExecution/DataDocStatementExecution.tsx
This reverts commit 7a256797ffdbe6c2ba60376fd0f864c96fa236c5.
User has reported that the estimate has been inaccurate (for presto) and could be misleading
> fix: Revert "feat: add estimated time for query execution (#1158)"

- docs_website/docs/configurations/infra_config.md
- querybook/config/querybook_default_config.yaml
- querybook/server/app/auth/ldap_auth.py
- querybook/server/env.py
In our company, LDAP has attribute names different from standards.
There are additional LDAP configs for those case in flask app builder
- https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap
querybook was implemented on top of flask without fab. so I added some more configs for ldap integrations.
config attribute naming is based on the page below
- https://docs.bmc.com/docs/fpsc121/ldap-attributes-and-associated-fields-495323340.html
> add more configurations for ldap integration

- helm/Chart.yaml
- helm/templates/scheduler/scheduler-deployment.yaml
- helm/templates/web/web-deployment.yaml
- helm/templates/web/web-ingress.yaml
- helm/templates/web/web-service.yaml
- helm/templates/worker/worker-deployment.yaml
- helm/values.yaml
- add ingress template to make http/https endpoint on webserver component
- add extraEnv props. to inject common environment variables to all the pods of components
- fix pod assigning configs on `values.yaml` to valid position (all the pod templates actually has same global configs)
> update querybook helm charts

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
Display the actual error message from the sql-formatter instead of a general error message.
> chore: display error message from sql-formatter

- querybook/server/lib/query_analysis/transpilation/transpilers/sqlglot_transpiler.py
Supports Microsoft SQL Server transpiling by adding a mapping from Querybook's `mssql` language to [Sqlglot's `TSQL`](https://github.com/tobymao/sqlglot/blob/main/sqlglot/dialects/__init__.py#L78) dialect.
> fix: Enable mssql transpiling

- querybook/server/tasks/run_datadoc.py
- querybook/server/tasks/run_query.py
Adds more descriptive error messages when running a datadoc fails. This error message contains the exact error from the query cell, and the name of the failed query cell to help pinpoint the location of the error.
> feat: add descriptive error msgs

- querybook/server/lib/dag_exporter/exporters/demo_dag_exporter.py
- querybook/server/lib/export/exporters/gspread_exporter.py
- querybook/server/lib/form/__init__.py
- querybook/server/lib/metastore/loaders/glue_data_catalog_loader.py
- querybook/server/lib/metastore/loaders/hive_metastore_loader.py
- querybook/server/lib/metastore/loaders/thrifthive_metastore_loader.py
- querybook/server/lib/query_executor/executor_template/templates.py
- querybook/tests/test_lib/test_form/test__init__.py
- querybook/webapp/ui/SmartForm/SmartForm.tsx
- querybook/webapp/ui/SmartForm/formFunctions.ts
- querybook/webapp/ui/SmartForm/types.ts
Previously StructFormField was created by a dictionary of values (kwargs), but when we send the form fields to the frontend they would be come unordered. This change would now use `args` which is ordered. The change is backward compatible since StructFormField would still accept kwargs and then convert them into array
> feat: make struct form fields ordered

- querybook/webapp/components/DataTableView/DataTableHeader.tsx
- querybook/webapp/const/tooltip.ts
- querybook/webapp/ui/Tag/Tag.tsx
**Issue**
For long tag tooltips, it is always in single line and will be cut by the table view modal. 
**Fix**
Querybook is using [Balloon.css](https://kazzkiq.github.io/balloon.css/) for tooltips, it acutally supports the length property `data-balloon-length` which can help with this issue.
before:
after:
> fix: add tooltip length

- querybook/webapp/components/DataElement/DataElementDescription.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- when there is no column description, we'll show the associated data element's description.
- make the table property clickable if it's a link
**with column description**
**without column description**
> feat: display data element description as column description

- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
`value` could be null. adding check before test if it's a link.
> fix: check nullish of table property value

- querybook/server/datasources/data_element.py
- querybook/server/datasources/metastore.py
- querybook/server/logic/data_element.py
- querybook/server/logic/tag.py
- querybook/webapp/components/DataTableStats/DataTableColumnStats.tsx
- querybook/webapp/components/DataTableTags/DataTableTags.tsx
- querybook/webapp/components/DataTableTags/TableTagSelect.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.scss
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewMini/TablePanelView.tsx
- querybook/webapp/const/metastore.ts
- querybook/webapp/resource/table.ts
- querybook/webapp/ui/Tag/HoverIconTag.tsx
- querybook/webapp/ui/Tag/Tag.scss
some bug fixes
- can't add tags whose name contains space and underscore
- too many api calls on the column tab in table view. Combined the tag, data element and column stats into one api call
- unnecessary wrap of the tag name on the left sidebar mini table view. Change it to nowrap and also hide tag type in the mini view.
Also removed the expand/collapse toggle button and move the column name before the column type
> fix: some bug fix related to tag and data element

- querybook/server/datasources/datadoc.py
- querybook/server/datasources/query_execution.py
- querybook/server/datasources_socketio/datadoc.py
- querybook/server/datasources_socketio/helper.py
- querybook/server/logic/datadoc_collab.py
- querybook/server/tasks/run_datadoc.py
- requirements/base.txt
Recently there is a version upgrade of `python-socketio` to [v3.8.0](https://github.com/miguelgrinberg/python-socketio/blob/main/CHANGES.md) breaks Querybook due to this [change](https://github.com/miguelgrinberg/python-socketio/commit/1cadada02dd7dc1eb96f45e88cbec67e1a393db3#diff-f48cfe03e710293c3fc425967c50df35894a72397328da6bcf4ecbfe5e831836L271) , which remove the `**kwargs` from the  `.emit` function, while we're passing a parameter of `broadcast` today. 
The `broadcast` parameter is actually on the `flask_socketio.emit`, not on the [SocketIO.emit()](https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/src/flask_socketio/__init__.py#L401) ,while we're using the latter.
> fix: remove broadcast from socketio.emit

- querybook/server/datasources/query_execution.py
- querybook/server/lib/query_executor/clients/presto.py
- querybook/server/lib/query_executor/executor_template/templates.py
- querybook/webapp/ui/SmartForm/SmartForm.tsx
- added force terminate when cancelling queries
- added timeout config for presto
- make sure numberfield always return a number
> feat: add configurable timeout to querybook

- docs_website/docs/changelog/breaking_change.md
- package.json
- querybook/migrations/versions/7f6cdb3621f7_add_data_element_support.py
- querybook/server/models/data_element.py
the default charset may not be utf8, which doesn't support utf8 chars in the description column
if the table has already been created, please run below to update
`ALTER TABLE data_element CONVERT TO CHARACTER SET utf8mb4;`
> fix: update data_element table charset to utf8

- querybook/webapp/components/Search/EntitySelect.tsx
- querybook/webapp/components/Search/SearchOverview.tsx
forgot to check `validateEntity` could be null
> fix: EntitySelect

- querybook/server/logic/data_element.py
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/Search/SearchResultItem.tsx
remove the duplicate description
also 
- update the search_data_elements_by_keyword to `startswith`,
- change the limit to 20
- hide metastore filter if there is only one
> fix: dup table description in table search

- querybook/server/tasks/run_datadoc.py
scheduled datadoc will fail when there is a empty query cell in the doc. Here we skip empty cells.
> fix: skip empty query cells when run datadoc

- package.json
- querybook/webapp/components/DataDocLeftSidebar/DataDocLeftSidebar.scss
- querybook/webapp/components/DataDocLeftSidebar/DataDocLeftSidebar.tsx
- querybook/webapp/components/EnvironmentAppSidebar/EnvironmentAppSidebar.tsx
- querybook/webapp/hooks/useResizeToCollapse.ts
make datadoc table of contents sidebar resizable, only on the right side
> feat: make datadoc table of contents sidebar resizable

- package.json
- querybook/server/datasources_socketio/helper.py
- querybook/server/tasks/run_query.py
and also remove the query execution decr stats events
> fix: use incr for ws disconnect stats events

- querybook/server/const/data_element.py
- querybook/server/datasources/admin.py
- querybook/server/datasources/metastore.py
- querybook/server/logic/data_element.py
- querybook/server/logic/demo.py
- querybook/server/models/admin.py
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/const/metastore.ts
- also fixed some issues with string data element
- added tags and data element in demo
- hide data element search if it is not available
> feat: add data elements to demo

- querybook/server/datasources/data_element.py
- querybook/webapp/components/DataTableNavigator/DataTableNavigator.tsx
- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.scss
- querybook/webapp/components/DataTableNavigator/DataTableNavigatorSearch.tsx
- querybook/webapp/components/Search/EntitySelect.tsx
- querybook/webapp/resource/table.ts
- querybook/webapp/stylesheets/_utilities.scss
filter by data element on the sidebar
data element now also displays description (2 lines at most):
> feat: add data element on the sidebar, show descriptions

- querybook/webapp/components/Search/SearchOverview.tsx
metastoreId can be null'ed until user interacts with it on the sidebar
> fix: metastoreId can be ill defined

- querybook/server/lib/query_executor/base_executor.py
- querybook/server/lib/query_executor/clients/trino.py
Basically, if a Trino query fails fast enough that the `poll()` function never runs successfully, the `meta_info` for the execution won't be captured, containing the Trino tracking URL. Something like "asdfg" as a query would trigger this because Trino doesn't need to do any metastore lookups before failing the query. Whereas queries that are slower to fail will go through 2 or more poll() iterations, and the successful ones will update the meta_info prior to the exception.
This PR fixes the issue by catching exceptions and updating the tracking URLs, as well as ensuring that on_statement_update() get a copy of meta_info when an exception occurs during the first poll()
> fix: Ensure meta_info is updated when an exception occurs

- querybook/server/lib/elasticsearch/search_table.py
Adjust the table search rank score
- Add more weights for high `importance_score` and `golden` tables
- Change the boost mode from `multiply` to `sum` to honor more on the `script_score` 
- Boost phrase matches from table name, table/column/data_element descriptions`
> feat: tune table search ranking

- querybook/webapp/components/Search/SearchResultItem.scss
- querybook/webapp/components/Search/SearchResultItem.tsx
wrapping long table names/any search res title
> ui: long table name fix

- querybook/server/models/comment.py
- querybook/server/models/datadoc.py
- querybook/server/models/metastore.py
meeting requirements below
Support comment and comment threads (1 level)
Each comment can be edited after posted
Each comment can be attached to a datadoc cell, or a whole table (make sure this system is extensible if we want to add commenting elsewhere)
When a cell is cloned or copied, the comment is not copied. When a cell is cut, the comment is moved
Support reactions, like Slack
Support richtext in comments
> ui: comment db updates

- querybook/webapp/lib/chart/chart-meta-processing.ts
After aggregation, the value may become null for some categories, which will lead to below exception
> fix: showing values from a null value

- querybook/server/datasources/ai_assistant.py
- querybook/server/lib/ai_assistant/ai_assistant.py
- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- requirements/ai/langchain.txt
the actual ai helper function may be executed in another thread because of streaming, so it wont be able to get the current_user from flask_login. Here we're passing it over.
> pass user_id to the ai help functions

- querybook/server/datasources/ai_assistant.py
- querybook/server/lib/ai_assistant/ai_assistant.py
- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/webapp/lib/datasource.ts
1. send errors through the event stream and show it on frontend with toast
2. adopted the SSE stream format
3. using EventSource on frontend to better handling the stream, instead of fetch
> feat: add error handling and use EventSource for AI assistant

- .github/workflows/pythontests.yml
- docs_website/docs/integrations/plugins.md
- package.json
- plugins/api_plugin/__init__.py
- plugins/api_plugin/test.py
- plugins/monkey_patch_plugin/__init__.py
- plugins/monkey_patch_plugin/demo.py
- querybook/server/datasources/__init__.py
- querybook/server/datasources/admin.py
- querybook/server/lib/patch.py
- querybook/server/logic/demo.py
Adding a monkey patch and api plugin, so that people can override some of the api endpoints and functions to meet their needs. E.g. for the demo setup, we may want to have a different setup internally.
> Add monkey patching and api  plugin

- Dockerfile
Got below error when building the docker image due to npm not found, seems like something wrong with nodejs 16 installation. Upgrading to v18 works
```
=> CACHED [ 2/11] RUN rm -rf /var/lib/apt/lists/*     && apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install --no-insta  0.0s
=> ERROR [ 3/11] RUN npm i -g npm@8.5.0     && npm i -g yarn@^1.22.10     && npm explore npm --global -- npm install node-gyp@9.0.0       0.3s
------
> [ 3/11] RUN npm i -g npm@8.5.0     && npm i -g yarn@^1.22.10     && npm explore npm --global -- npm install node-gyp@9.0.0     && yarn config set cache-folder /mnt/yarn-cache/cache     && yarn config set yarn-offline-mirror /mnt/yarn-offline-mirror:
#0 0.264 /bin/sh: 1: npm: not found
```
> upgrade nodejs from v16 to v18

- package.json
- querybook/config/elasticsearch.yaml
Table/column/data element/board descriptions are now indexed using a case-sensitive analyzer, which may cause some search queries to fail.
Here we're updating the filter of the analyzer. 
**NOTE**:  all impacted documents will need to be reindexed.
> add lowercase filter to user_content_analyzer

- querybook/server/datasources/__init__.py
- querybook/server/lib/patch.py
If the module doesn't exist, it will cause the service failure. Here we'll catch the error and just ignore it.
> fix: Ignore monkey patch/api plugin import error

- helm/templates/_helpers.tpl
- helm/templates/scheduler/scheduler-deployment.yaml
- helm/templates/secret.yaml
- helm/values.yaml
Fixes: https://github.com/pinterest/querybook/issues/1259
Allows a user to specify the name of an existing Kubernetes Secret, or defaults to the secret specified in `values.yaml`
> feat: Injectable Secrets into the Helm Chart

- package.json
- querybook/config/querybook_public_config.yaml
- querybook/server/datasources/ai_assistant.py
- querybook/server/lib/ai_assistant/ai_assistant.py
- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/webapp/components/AIAssistant/AIModeSelector.tsx
- querybook/webapp/components/AIAssistant/QueryGenerationButton.tsx
- querybook/webapp/components/AIAssistant/QueryGenerationModal.scss
- querybook/webapp/components/AIAssistant/QueryGenerationModal.tsx
- querybook/webapp/components/AIAssistant/TableSelector.tsx
- querybook/webapp/components/AIAssistant/TextToSQLModeSelector.tsx
- querybook/webapp/components/DataDoc/DataDoc.scss
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.scss
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/TranspileQueryModal/QueryComparison.tsx
- querybook/webapp/stylesheets/_utilities.scss
- For new query generation, it will ask for selecting tables first.
- For query editing, it will parse the tables from the query.
https://github.com/pinterest/querybook/assets/8308723/3bd096bf-6235-42ac-8420-0063d4632413
> feat: add LLM powered text2sql support

- querybook/migrations/versions/4c70dae378f2_add_comment_feature.py
- querybook/server/const/comment.py
- querybook/server/datasources/comment.py
- querybook/server/logic/comment.py
- querybook/server/models/comment.py
- querybook/webapp/components/DataTableView/DataTableHeader.scss
- querybook/webapp/components/DataTableView/DataTableHeader.tsx
- querybook/webapp/const/comment.ts
- querybook/webapp/redux/comment/action.ts
- querybook/webapp/redux/comment/reducer.ts
- querybook/webapp/redux/comment/types.ts
- querybook/webapp/resource/comment.ts
- querybook/webapp/ui/Comment/AddReactionButton.tsx
- querybook/webapp/ui/Comment/Comment.tsx
- querybook/webapp/ui/Comment/CommentButton.tsx
- querybook/webapp/ui/Comment/Comments.scss
- querybook/webapp/ui/Comment/Comments.tsx
- querybook/webapp/ui/Comment/OpenThreadComment.tsx
- querybook/webapp/ui/Comment/Reactions.tsx
- querybook/webapp/ui/Comment/ThreadComment.tsx
- querybook/webapp/ui/Popover/Popover.tsx
- querybook/webapp/ui/RichTextEditor/RichTextEditor.tsx
enable archive comment + add archived comment ui
add clearing to draftjs editor (known issue by draftjs)
tried to make reactions unique in db but db will say some emojis are the same
using formik bc react doesnt like state change along with forwardref?
add commenting for tables
https://github.com/pinterest/querybook/assets/29313935/25d64da0-2c92-495f-b1dd-b6bc8d946f5b
> feat: enable archive comment + wrap up

- package.json
- querybook/webapp/__tests__/lib/stream.test.ts
- querybook/webapp/components/QueryCellTitle/QueryCellTitle.tsx
- querybook/webapp/hooks/useStream.ts
- querybook/webapp/lib/datasource.ts
- querybook/webapp/lib/stream.ts
Previously when the stream ends with non-empty buffer, the data in the buffer will not be flushed to the final result.
> fix: delta stream  parser

- querybook/webapp/lib/datasource.ts
when there is error occurred, we'll also need to pass parser result back, otherwise, it will get undefined error
> fix: crash on stream parser error

- package.json
- querybook/webapp/components/QueryCellTitle/QueryCellTitle.tsx
Fix it by only update the title when is streaming and title is not empty
> Fix: query title disappears when opening a datadoc

- package.json
- querybook/webapp/components/AIAssistant/AutoFixButton.scss
- querybook/webapp/components/AIAssistant/AutoFixButton.tsx
- querybook/webapp/components/AIAssistant/QueryGenerationModal.tsx
- querybook/webapp/hooks/useStream.ts
- querybook/webapp/lib/datasource.ts
add support of streaming cancellation
also only handle the query generation keydown event when not streaming
> fix: only handle the query generation keydown event when not streaming

- package.json
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- If column description is empty and the column has associated data element, use data element's description as the column description
- Add column filter support. People can filter out columns from the table schema if they are not needed.
> feat: adopt data element in text2sql prompt

- querybook/server/lib/query_executor/clients/sqlalchemy.py
- querybook/server/lib/query_executor/executor_template/templates.py
add `impersonate` parameter to sqlalchemy executor. use proxy user as username of the connection if `impersonate` is true
> feat: use proxy user as username to sqlalchemy executor

- docs_website/docs/changelog/breaking_change.md
- package.json
- querybook/server/lib/query_analysis/validation/validators/presto_optimizing_validator.py
- querybook/tests/test_lib/test_query_analysis/test_validation/test_validators/test_presto_optimizing_validator.py
* Update version of Querybook since query optimization pr has some breaking changes
* Update `PrestoOptimizingValidator` class to be able to override `PrestoExplainValidator` object
> Update querybook version, fix PrestoOptimizingValidator

- querybook/webapp/components/Search/SearchContainer.tsx
- querybook/webapp/components/UIGuide/QuerybookSidebarUIGuide.tsx
> fix: UI Tutorial 8-11 now focuses on page components

- querybook/webapp/components/DataTableViewWarnings/DataTableViewWarnings.tsx
This PR fixes a bug where a table warning or error would display on the wrong table. It would display on the table that the page was most recently refreshed on. This bug would only occur when the "Show full view" setting is enabled.
> fix: table warning displaying on wrong table

- querybook/server/logic/board.py
This PR fixes a bug where when a new owner was assigned for a board, the board's "owner_uid" parameter was not being reassigned. This would result in an error on the second attempt, because an editor would be created for the previous owner but the ownership would not be reassigned. Therefore, it would try to create a second editor, which results in a duplicate entry.
> fix: Board Ownership Transfer did not reassign owner

- querybook/server/logic/elasticsearch.py
This PR fixes a small bug in the `querybook.server.logic.elasticsearch._bulk_insert_users()` function. The `get_users_iter` function used to return a `dict` object representation of the users in the database, but the `_bulk_insert_users` function tries to access the `is_group` attribute found in the `User` SQLAlchemy model.
Running this function with users already present in the database (usually through the `init_es.py` script invoked by `--initdb`) results in the following error:
```
Traceback (most recent call last):
File “<stdin>“, line 1, in <module>
File “/opt/querybook/querybook/server/logic/elasticsearch.py”, line 725, in _bulk_insert_users
if not user.is_group:
AttributeError: ‘dict’ object has no attribute ‘is_group’
```
The proposed fix is to return `User` instances from the …
> fix: init_es.py script not completing due to AttributeError

- querybook/server/lib/query_executor/base_executor.py
Adding these properties to use query execution metadata within custom executor logic
> Add query_execution_id and execution_type as properties to QueryExecutorBaseClass

- querybook/server/const/metastore.py
- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/logic/metastore.py
load table warnings from metastore if there is any.
For warnings from metastore, the created_by will be leave it as empty.
> feat: load table warnings from metastore

- querybook/server/lib/query_executor/clients/trino.py
- querybook/server/lib/query_executor/executor_template/templates.py
Adding username and password authentication for the trino client (fixes https://github.com/pinterest/querybook/issues/829)
Like the presto client-
[querybook/querybook/server/lib/query_executor/clients/presto.py](https://github.com/pinterest/querybook/blob/1e3d01e8a8177f7c4a0031b681f4e1e8d95b3f76/querybook/server/lib/query_executor/clients/presto.py#L12)
> Add Username + Password Authentication for Trino Client (fixes #829)

- Dockerfile
The Docker build was failing this morning with an error:
```
#10 15.97 E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64.deb  404  Not Found [IP: 104.22.4.26 443]
```
Per [this issue](https://github.com/nodesource/distributions/issues/1631), it might be fixed on their side now.  But since Nodesource has a new repository and the installation scripts `setup_XX.x` are no longer supported, I've updated to use the new repository to avoid future issues.
I've adapted the instructions here: https://github.com/nodesource/distributions/wiki/How-to-migrate-to-the-new-repository
> fix: Migrate to new Nodesource repository

- querybook/webapp/components/DataDoc/DataDoc.scss
DataDocs with wide result tables cause the entire page to scroll horizontally:
**Before:**
This isn't an issue in Chrome because there's a special case hardcoded for it in [DataDocContentContainer](https://github.com/pinterest/querybook/blob/master/querybook/webapp/components/DataDoc/DataDocContentContainer.tsx#L7).
This PR fixes the issue by enabling overflow for `.data-doc-content-container`, and doesn't break anything for Chrome.
Tested this change in Firefox and Safari.
**After:**
> fix: Fix DataDoc contents overflow in non-Chrome browsers

- containers/bundled_querybook_config.yaml
- docs_website/docs/integrations/add_ai_assistant.md
- package.json
- querybook/config/querybook_default_config.yaml
- querybook/server/datasources/search.py
- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/server/lib/ai_assistant/tools/table_schema.py
- querybook/webapp/components/AIAssistant/AutoFixButton.tsx
- move the "from logic import vector_store as vs_logic" as delayed import to fix the issue of can't find langchain module when ai assistant is not enabled
- when the response format of auto fix is not as expected, show the unformatted response anyway
- Try to not include table/column description or other metadadata if prompt is too long
- Pass prompt length to `_get_llm`, so it can be used to determine which llm model to use
- Fix for some cases the table name in the vector store is not a full table name.
- update the docs of installing langchain package
> fix: some small changes and fixes for AI assistant

- querybook/webapp/components/DataDoc/DataDoc.scss
This reverts commit 18c86a6010fbc9d4fa8e708f8ca3343718915a6a.
It caused datadoc with many data cells can't be fully loaded 
@baumandm
> Revert "fix: Fix DataDoc contents overflow in non-Chrome browsers (#1332)"

- querybook/server/lib/elasticsearch/search_table.py
- querybook/server/lib/query_analysis/validation/base_query_validator.py
- querybook/server/lib/query_analysis/validation/validators/base_sqlglot_validator.py
- querybook/server/lib/query_analysis/validation/validators/metadata_suggesters.py
- querybook/server/lib/query_analysis/validation/validators/presto_explain_validator.py
- querybook/server/lib/query_analysis/validation/validators/presto_optimizing_validator.py
- querybook/tests/test_lib/test_query_analysis/test_validation/test_validators/test_presto_optimizing_validator.py
Add column name suggestions to presto optimizing validator:
1. determine if error message returned by presto explain validator is a column name error by searching the regex 
2. if so, get invalid column name, and use elasticsearch fuzzy search to search for the correct column name in all of the tables used in the query
3. if only 1 result is returned by the elasticsearch query (meaning that there is one possible correct column name) - return that column name as a suggestion
> Add column name suggestions to presto validator

- package.json
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/server/lib/ai_assistant/prompts/table_select_prompt.py
- querybook/webapp/components/AIAssistant/QueryGenerationModal.tsx
- querybook/webapp/components/AIAssistant/TableSelector.tsx
- querybook/webapp/components/AIAssistant/TableTag.tsx
- querybook/webapp/components/CodeMirrorTooltip/TableTooltip.tsx
When AI finds tables for the question, it generates the query using those tables directly without asking user.
Now we are changing it to ask user to confirm the tables before query generation.
https://github.com/pinterest/querybook/assets/8308723/bbaea188-9b7e-447d-91f7-17e2fbb8b5c0
> feat: ask users to confirm tables before query generation

- querybook/server/logic/demo.py
- querybook/server/logic/schedule.py
- querybook/server/models/schedule.py
The task type was being stored in the db as `"ScheduleTaskType.PROD"` rather than the expected `"prod"`. This was causing newly created tasks to be filtered out in the `AdminTask` component ([link](https://github.com/pinterest/querybook/blob/master/querybook/webapp/components/AppAdmin/AdminTask.tsx#L57-L72)).
> fix: store the task type value rather than enum when creating a task

- querybook/server/lib/elasticsearch/search_table.py
- querybook/server/lib/query_analysis/validation/decorators/base_sqlglot_validation_decorator.py
- querybook/server/lib/query_analysis/validation/decorators/base_validation_decorator.py
- querybook/server/lib/query_analysis/validation/decorators/metadata_decorators.py
- querybook/server/lib/query_analysis/validation/validators/presto_optimizing_validator.py
- querybook/server/logic/admin.py
- querybook/tests/test_lib/test_query_analysis/test_validation/test_validators/test_presto_optimizing_validator.py
* Update all decorators to inherit from a new `BaseValidationDecorator`
* Update table suggestions to match engine's metastore_id
> Refactor validation decorators

- .github/workflows/lint.yml
- querybook/server/lib/export/base_exporter.py
- querybook/server/lib/export/exporters/gspread_exporter.py
- querybook/server/lib/export/exporters/python_exporter.py
Google sheets export:
* Add the query execution link to the Google sheet url
* Add the Google sheet url to the statement_execution's meta_info
Python export:
* Add the query execution link as a comment to the python file
> Add query execution links to exporter results

- querybook/scripts/runservice
We've encountered issues where workers would stop receiving tasks after an error message like this:
```
consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 332, in start
blueprint.start(self)
```
I was able to reproduce this locally via Docker by manually bouncing the Redis container.
After some research, we came across suggestions to disable the heartbeat/gossip/mingle features of Celery.  In my local testing it appears this change eliminates (or at least reduces) the issue where the workers cannot reconnect to Redis after a connection failure.
We have been running this in production for over a month and everything works as expected, …
> fix: Update runservice worker scripts to disable unneeded features

- querybook/server/app/flask_app.py
Environment variables are loaded in as strings, which results in the following error for loading `QuerybookSettings.TABLE_MAX_UPLOAD_SIZE`
```querybook_web            | [2023-11-16 Thu 14:18:16] - /opt/querybook/querybook/server/app/datasource.py - ERROR   "'>' not supported between instances of 'int' and 'str'"
querybook_web            | Traceback (most recent call last):
querybook_web            |   File "/opt/querybook/querybook/server/app/datasource.py", line 84, in handler
querybook_web            |     results = fn(**kwargs)
querybook_web            |   File "/opt/querybook/querybook/server/datasources/event_log.py", line 18, in log_frontend_event
querybook_web            |     events = json.loads(flask.request.data)
```
This fix casts the table max upload size variable to an int …
> fix: cast table max upload size to int

- docs_website/docs/changelog/breaking_change.md
- docs_website/docs/integrations/add_table_upload.md
- querybook/server/lib/metastore/loaders/hive_metastore_loader.py
- querybook/server/lib/table_upload/exporter/s3_exporter.py
- querybook/webapp/components/TableUploader/TableUploaderForm.tsx
- Explicitly call out that the table is managed when `use_schema_location=False` for s3 table uploader. 
- Get the actual table location from metastore for data uploading for managed tables
- Fix the logic of checking `is_external`. Previously `is_external` will be `False` when `use_schema_location` is True, which supposed to be True (external table), as it is specifying location.
```is_external = not self._exporter_config.get("use_schema_location", False)```
> fix: s3 table upload location

- querybook/webapp/components/QueryEngineStatusButton/QueryEngineStatusButton.tsx
- querybook/webapp/ui/Menu/Menu.tsx
Environments with many Query Engines break the Query Engine status popover, so this PR adds a `max-height` and a scrollbar to keep everything on the screen.
**Before:** 😿 
**After:** 😸
> fix: Add scroll bar to Query Engine Status popover

- querybook/server/clients/google_client.py
- querybook/server/lib/metastore/loaders/sqlalchemy_metastore_loader.py
- querybook/server/lib/query_executor/clients/bigquery.py
- querybook/server/lib/query_executor/executor_template/templates.py
- requirements/engine/bigquery.txt
This Merge request allow the use of sqlalchemy-bigquery as a metastore for bigquery engine.
Also bump bigquery requirements files and add sqlalchemy-bigquery dependency.
Allow use of empty google credentials for bigquery engine : In case of running in GKE cluster, we can use in cluster service account with workload identity to authenticate to google.
It Fix : https://github.com/pinterest/querybook/issues/517
> Bigquery sqlalchemy metastore

- querybook/server/app/auth/ldap_auth.py
- querybook/server/app/auth/oauth_auth.py
- querybook/server/app/auth/okta_auth.py
- querybook/server/app/auth/password_auth.py
- querybook/server/logic/user.py
when sending an object insdie the username like:
```
POST /ds/login/ HTTP/1.1
Host: localhost:10001
{"username":{"test":1},"password":"test"}
```
will get
```
"(pymysql.err.ProgrammingError) (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''test': '1'} \\n LIMIT 1' at line 3\")\n[SQL: SELECT user.password AS user_password, user.id AS user_id, user.username AS user_username, user.fullname AS user_fullname, user.email AS user_email, user.profile_img AS user_profile_img, user.deleted AS user_deleted, user.is_group AS user_is_group, user.properties AS user_properties \nFROM user \nWHERE user.username = %(username_1)s \n LIMIT %(param_1)s]\n[parameters: {'username_1': {'test': 1}, 'param_1': …
```
> fix: possible unauthenticated SQL injection when login

- querybook/server/logic/user.py
Currently, `create_or_update_user_group()` sets the group description directly inside the `properties` dict, but only the values of the `public_info` key are exposed via the API.
This change stores the description in the correct location so that the UI can display it.
> fix: Store group description in `public_info`

- querybook/server/datasources/metastore.py
- querybook/server/logic/metastore.py
- querybook/webapp/components/DataTableStats/DataTableColumnStats.tsx
- querybook/webapp/components/DataTableView/DataTableView.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableColumnCard.tsx
- querybook/webapp/components/DataTableViewColumn/DataTableViewColumn.tsx
- querybook/webapp/resource/table.ts
* Update column stats UI to show table column stats as tags (rather than additional rows)
* Add ability to sort columns by usage
* Query all table column details from table column page to be able to sort columns by usage
> feat: update column stats ui, add sort by usage to columns

- package.json
- querybook/server/lib/export/exporters/gspread_exporter.py
Add an option in google sheet exporter to clear the sheet. By default it is `false` (to make it consistent as before)
> fix: add a clear_sheet parameter for google sheet exporter

- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
Current:
The survey triggers on any cell execution. It means you can just open a DataDoc, hit Run button and the survey will show up asking how easy it was to create the query (and no query authoring happened). 
Updated as: 
Survey asking for query_authoring experience is shown only after user created new or modified existing query and ran it.
> fix: modify trigger for query_authoring survey

- Dockerfile
Previously, the `pip install` command in the Dockerfile ended in `|| true`, so it never failed.  I think the purpose was to make `local.txt` optional, but it also covers up any errors installing packages.
This removes `|| true` and instead makes `local.txt` optional by checking to see if the file exists.
> chore: Update pip install command

- querybook/server/logic/schedule.py
Currently Data Doc tasks are being created with `task_type` `"prod"` instead of `"user"`.  
This is because the `get_schedule_task_type()` function expects the Celery task name (`tasks.run_datadoc.run_datadoc`), not the task name (`run_data_doc_#`).
> fix: Fix create task schedule task_type

- querybook/webapp/components/Survey/Survey.tsx
- querybook/webapp/const/analytics.ts
- querybook/webapp/hooks/useTrackView.ts
this is to add logging whenever a survey event triggers, both surface info and meta are logged.
> feat: enable impression logging of survey events

- package.json
- querybook/webapp/lib/richtext/index.tsx
Currently, if a user inputs a `javascript:alert()` into the URL, it would XSS inject any users on that doc who clicks the link. This fix is backward compatible where all non-http/https urls will cease to work
> fix: XSS injection with Querybook RichTextEditor

- querybook/webapp/components/DataDoc/DataDoc.scss
- querybook/webapp/components/DataDoc/DataDocCellControl.tsx
DataDoc cells have ⏫ ⏬ buttons to move them up or down in the DataDoc, but it's impossible to click on the ⏬ button because the next cell's ⏫ button always gets in the way.
Each cell has a header and a footer row of buttons, and the footer row overlaps the header row of the next cell.  They are set to `opacity: 0` unless the cell is being hovered over, so you never see both at the same time.  However, the issue is that elements on the page are automatically stacked bottom up, so that as you move down the page, each element stacks on top of earlier elements. Hovering doesn't care about order, so both the footer and the next header are both receiving the `:hover` style at the same time, and the stacking order puts the header on top of the footer, so you can't click the ⏬ button.
I fixed …
> fix: Fix DataDoc cell move down button

- querybook/webapp/lib/query-result/analyzer.ts
I know that there's the option to add custom column analyzers, but I think sum is common enough to be supported natively and appear at the top of the Quick Insights view of a column.
> fix: add native sum column analyzer

- docs_website/docs/integrations/add_notifier.mdx
- querybook/server/lib/notify/all_notifiers.py
- querybook/server/lib/notify/notifier/noop_notifier.py
Fixes #733:
- configures the two built-in notifiers (Slack, Email) to automatically load themselves if the corresponding configs are set
- adds a `NoopNotifier` that enables itself if no other notifiers are enabled⸺it outputs notifications to the server logs
- updated docs
> feat: Auto-load built-in notifiers if configured

- querybook/server/lib/metastore/utils.py
- querybook/webapp/components/AppAdmin/AdminMetastore.tsx
Adds support for wildcard prefixes on table names in the ACL rules.  E.g. `querybook2.query_*` matches any tables in the `querybook2` schema starting with `query_`.
Also added a helper tooltip to the admin UI to document the supported formats, since I don't think there's any other documentation on how to use this feature.
> fix: Metastore ACL support for wildcard prefix match

- docs_website/docs/changelog/breaking_change.mdx
- docs_website/docs/configurations/infra_config.mdx
- package.json
- querybook/config/querybook_default_config.yaml
- querybook/server/app/flask_app.py
- querybook/server/env.py
Currently we allow all origins to connect to the websocket server. This change is to change the behavior for production to be configurable with a list of origins.
> fix: enable websocket cors for production

- querybook/server/logic/metastore.py
The `table_updated_at`/`table_updated_by` fields aren't being populated correctly in the database.
> fix: Correct mapping for table_updated_at/table_updated_by

- querybook/webapp/components/UIGuide/QuerybookSidebarUIGuide.tsx
Found a typo in the Sidebar guide.
> fix: typo in QuerybookSidebarUIGuide

- querybook/webapp/components/SearchAndReplace/CodeMirrorSearchHighlighter.tsx
- querybook/webapp/components/SearchAndReplace/SearchAndReplaceBar.tsx
Previously, there was a bug that prevented the focus moving to the first match after the search term was updated (it moved the index of the first match of the previous term instead). 
This PR also includes a change that allows you to continuously scroll through match results (i.e. clicking "Previous Result" on the first match moves to the last match and vice versa). 
https://github.com/pinterest/querybook/assets/5560701/b80ee033-1ed8-48fb-8311-6d7193808d3e
> fix: move to first match on search term change

- package.json
- querybook/config/elasticsearch.yaml
- querybook/server/datasources/search.py
- querybook/server/lib/elasticsearch/search_utils.py
- querybook/server/lib/elasticsearch/suggest_table.py
- querybook/server/logic/elasticsearch.py
- querybook/webapp/components/AIAssistant/AICommandBar.tsx
- querybook/webapp/components/AIAssistant/AICommandInput.scss
- querybook/webapp/components/AIAssistant/AICommandInput.tsx
- querybook/webapp/components/AIAssistant/AICommandResultView.tsx
- querybook/webapp/const/keyMap.ts
- querybook/webapp/lib/utils/keyboard.ts
- querybook/webapp/resource/search.ts
- yarn.lock
- use "@" to mention what table to use
- if it's a new cell, it will populate a simple select * query for the first mentioned table automatically
- use cmd+/ to reset and open the commands
Also updated the table suggest API to cover non prefix suggestion.
package used: https://github.com/signavio/react-mentions
> feat: add @mention to select a table for the command input

- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/elasticsearch/suggest_table.py
previously we were using `full_name_ngram`, which only works for 3 or more chars. 
Here we use `full_name` , and only match for phrase prefix to ensure performance.
> fix: use match_phrase_prefix on full_name field for table suggestion

- querybook/config/elasticsearch.yaml
- querybook/server/datasources/search.py
- querybook/server/lib/elasticsearch/search_utils.py
- querybook/server/lib/elasticsearch/suggest_table.py
- querybook/server/logic/elasticsearch.py
- querybook/webapp/components/AIAssistant/AICommandBar.tsx
- querybook/webapp/components/AIAssistant/AICommandInput.tsx
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/resource/search.ts
in the PR https://github.com/pinterest/querybook/pull/1432/, we updated the table suggest api, which makes the performance really bad as it has no weight. this PR is to revert it and use `searchConcise` for the table mention instead.
Also fix and refactor a bit for the tables management in the AICommandBar component.
> fix: revert to use searchConcise for mentioning a table

- querybook/server/lib/notify/notifier/email_notifier.py
This fixes an issue with sending notifications to multiple email addresses (not users) at once.  The first email address would get the email, and the email would look like it was sent to all recipients, but it would not actually be delivered to the other email addresses.  `smtp.sendmail()` needs a list of addresses rather than the joined string in the message header.
This doesn't apply to any Querybook users who are added to the notification, because they are notified individually.
This StackOverflow helps explain the issue and the fix: https://stackoverflow.com/q/8856117.
> fix: Fix email notifications to multiple email addresses

- docs_website/docs/configurations/infra_config.mdx
- package.json
- querybook/server/app/flask_app.py
- querybook/server/env.py
This change is to 
> Prevents external sites from embedding your site in an iframe. This prevents a class of attacks where clicks in the outer frame can be translated invisibly to clicks on your page’s elements. This is also known as “clickjacking”.
Flask's [doc](https://flask.palletsprojects.com/en/2.3.x/security/#x-frame-options) suggests to use [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), but it has been obsoleted by [csp frame-ancestors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)
> fix: add csp header for iframe embedding

- querybook/webapp/components/DataTableViewSourceQuery/DataTableViewSourceQuery.scss
- querybook/webapp/components/DataTableViewSourceQuery/DataTableViewSourceQuery.tsx
-  Currently all Tier 1 tables have a link to the workflow creating the table. However this information is not included under the Source Query tab
Added workflow link to bottom of source query tab
> fix: move workflow link to source query tab

- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.scss
- querybook/webapp/components/DataTableViewOverview/DataTableViewOverview.tsx
- Add link icon to table links to make link attachments more obvious
> ui: Add icon to table links

- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/DataDocQueryExecutions/DataDocQueryExecutions.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/components/QueryComposer/QueryComposerExecution.tsx
- querybook/webapp/components/QueryExecution/QueryExecution.tsx
- querybook/webapp/components/QueryExecution/SamplingToolTip.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
If query is already sampled, we hide the user tip
> ui: Disable tip for sampled queries

- querybook/server/lib/metastore/base_metastore_loader.py
- querybook/server/logic/metastore.py
- querybook/server/logic/tag.py
We were facing some database perf issues, so I looked into it and the SQL query with the most waits was `INSERT INTO 'data_table_warnings'`:
We recently updated our metastore loader code to automatically add warnings to certain tables during the sync.  That explains why we're seeing it now, but it didn't seem right so I looked into it.
While most of the metastore sync executes as a single transaction per table, I realized data table warnings are being committed immediately.  I enabled database logging in SQLAlchemy and ran through the metastore sync, which helped identify a few other areas where separate transactions were being committed.
This PR fixes every case of a separate transaction in the `base_metastore_loader`'s `_create_table_table` function that I could detect.
1. Where …
> fix: Metastore sync tables with a single transaction

- README.md
Visit http://localhost:10001, Small fix correct URL is http://localhost:10001, not https://localhost:10001.
> docs: documentation typo https

- querybook/server/tasks/all_tasks.py
- querybook/server/tasks/disable_scheduled_docs.py
Because task type are enums but the column values are strings, the code fails to get the actual tasks.
> fix: Update task type to use str instead of enum

- docs_website/docs/integrations/add_surveys.mdx
- package.json
- querybook/config/querybook_public_config.yaml
- querybook/webapp/config.d.ts
- querybook/webapp/hooks/ui/useSurveyTrigger.tsx
- querybook/webapp/lib/survey/config.ts
- querybook/webapp/lib/survey/types.ts
Add a config of `trigger_duration` and `global_trigger_duration` to control the survey toast duration
> chore: make the survey duration configurable

- querybook/config/user_setting.yaml
- querybook/webapp/components/QueryEditor/BoundQueryEditor.tsx
- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/hooks/redux/useUserQueryEditorConfig.ts
- querybook/webapp/lib/codemirror/codemirror-copilot.ts
- querybook/webapp/lib/codemirror/index.ts
- Hide query suggestion feature toggle behind ‘User Settings’ value to allow users to control enablement
- Next PR will handle creating widget to display suggestions in the code editor when typing
> ui: Modify user settings for editor to enable query suggestions

- querybook/server/lib/form/__init__.py
- querybook/tests/test_lib/test_form/test__init__.py
Fixed erroneous typo and add documentation for clarity
> Fix: minor typo and add comment

- querybook/webapp/components/QueryEditor/QueryEditor.scss
- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/components/QueryEditor/themes.ts
- querybook/webapp/hooks/queryEditor/extensions/useKeyMapExtension.ts
- querybook/webapp/hooks/queryEditor/extensions/useOptionsExtension.ts
- removed indentWithTab and use insertTab instead
- removed indentWithTab in uiw/codemirror
- moved tab keymap to keymap extension instead since it doesn't tie with the tab editor option
- Updated theme to make gutter more visible
- Fixed issue with indent service at pos 0.
> Fix code editor tab behavior

- querybook/webapp/hooks/queryEditor/extensions/useKeyMapExtension.ts
- querybook/webapp/hooks/queryEditor/extensions/useOptionsExtension.ts
To honor user's settings of the tab size
1. insert a real tab if user chooses tab
2. insert spaces to the next tab stop if user chooses 2 or 4 spaces
> fix: codemirror editor  tab behavior

- package.json
- querybook/config/user_setting.yaml
- querybook/webapp/components/DataDocQueryCell/DataDocQueryCell.tsx
- querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx
- querybook/webapp/components/DataDocTableSamplingInfo/DataDocTableSamplingInfo.tsx
- querybook/webapp/components/QueryCellTitle/QueryCellTitle.tsx
- querybook/webapp/components/QueryComposer/QueryComposer.tsx
- querybook/webapp/components/QueryExecution/QueryError.tsx
- querybook/webapp/components/QueryExecution/SamplingToolTip.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/UserSettingsMenu/UserSettingsMenu.tsx
- querybook/webapp/lib/public-config.ts
- querybook/webapp/ui/Select/Select.tsx
Add the user settings for the default table sample rate, so that when a new query cell is added, the prefered sample rate will be selected by default if the table supports sampling
Also adding some util functions for the public configs
> feat: add table sample rate to user settings

- querybook/webapp/hooks/queryEditor/extensions/useSearchExtension.ts
forgot to scroll the current search result into the view when doing the search(cmd+f) and press prev/next
> fix: scroll the current search result into view

- querybook/webapp/components/DataDocStatementExecution/StatementResult.tsx
- querybook/webapp/components/QueryEditor/QueryEditor.tsx
- querybook/webapp/components/QueryRunButton/QueryRunButton.tsx
fix bugs
- the default sample rate in user settting could be empty, use the default sample rate from public config for that case
- it can paste into the query editor when it's readonly.
also updated the sampling message
> fix:  table sampling and editor bug

- docs_website/docs/user_guide/ai_assistant.mdx
- querybook/config/querybook_public_config.yaml
- querybook/server/const/ai_assistant.py
- querybook/server/datasources/search.py
- querybook/server/lib/elasticsearch/search_query.py
- querybook/server/lib/vector_store/base_vector_store.py
- querybook/server/logic/vector_store.py
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/config.d.ts
- querybook/webapp/lib/public-config.ts
- querybook/webapp/redux/search/action.ts
- querybook/webapp/resource/search.ts
Implement NLP query search to show similar queries. Same as NLP table search
> feat: nlp query search

- querybook/webapp/components/QueryEditor/QueryEditor.tsx
Issue: search & replace doesn't show up when the datadoc is readonly
Fix: make the editor readonly but editable (it will respond to keymap events still, but content can not be changed)
> fix: make sure the cmd-f still work on readonly docs

- querybook/webapp/ui/CodeHighlight/CodeHighlightWithMark.tsx
The `Show Query` button in the ad hoc editor is broken after the upgrade to Codemirror 6, because it still uses Codemirror 5 and the styles are not loaded.
**Repro:**
1. Run any query in the ad hoc editor
2. Click the `Show Query` button.
3. If it works correctly, reload the page
This is fixed by updating the `CodeHighlightWithMark` component to import the `lib/codemirror` module which loads all the Codemirror 5 styles, themes, etc.
If you open a DataDoc then switch back to the ad hoc page, this feature does work correctly.  This is because the DataDocQueryCell loads the `CodeHighlight` component which loads the `lib/codemirror` module.
**Before**
**After**
> fix: CodeMirror2 styles not appearing in CodeHighlightWithMark

- package.json
- querybook/server/lib/query_analysis/templating.py
- querybook/webapp/components/TemplateGuide/guides/predefined.md
Adding below predefined variable and function
- variable {{ ds }}: same as yesterday
- function {{ ds_add(ds, days) }}: add/sub days from ds
---
rendered as
---
rendered as
---
rendered as
> feat: add predefined template vairable ds and function ds_add

- querybook/server/lib/query_analysis/samples.py
sometimes the partition column might be missing from the table schema. Treat it as string type when generating the sample query.  
e.g. if the partition is `"dt=2015-01-01"`
current: `where dt=2015-01-01`
fixed: `where dt='2015-01-01'`
> fix: sample query generation

- .github/workflows/publish.yml
Publish to Registry is failing 
```
>> elgohr/Publish-Docker-Github-Action@master has been deprecated.
>> Please use elgohr/Publish-Docker-Github-Action@v4 for a blast in speed and security.
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: your account must log in with a Personal Access Token (PAT) - learn more at docs.docker.com/go/access-tokens
```
https://github.com/pinterest/querybook/actions/runs/13864816536/job/38801477190
> chore: update gihub action version

- package.json
- querybook/server/app/flask_app.py
- querybook/webapp/index.html
- querybook/webapp/index.scss
- querybook/webapp/lib/python/patch.ts
- querybook/webapp/lib/python/python-provider.tsx
- querybook/webapp/lib/python/python-worker.ts
- querybook/webapp/lib/python/task-queue.ts
- querybook/webapp/lib/python/types.ts
- querybook/webapp/lib/python/usePython.ts
- webpack.config.js
- yarn.lock
* add a simple queue to run the tasks in sequence. User can kick off multiple runs, and they will become pending and pushed to the queue
* add cancellation support by using shared array buffer, which requires [cross-origin isolated](https://developer.mozilla.org/en-US/docs/Web/API/Window/crossOriginIsolated) enabled.
* add a `progressCallback` to better track the execution status and execution count.
* add another helper function to get identifiers of a namespace to support auto completion.
> feat: add a task queue and support cancelling

- package.json
- querybook/webapp/components/DataDoc/DataDoc.tsx
- querybook/webapp/components/DataDocPythonCell/DataDocPythonCell.tsx
- querybook/webapp/components/DataDocPythonCell/PythonCellResultView.scss
- querybook/webapp/components/DataDocPythonCell/PythonCellResultView.tsx
- querybook/webapp/components/PythonKernelButton/guide.md
- querybook/webapp/lib/python/patch.ts
fix few bugs
- Resolve issues where the Matplotlib figure isn’t cleared after displaying it, causing subsequent figures to include previous content.
- Modify the image output to maintain an automatic height with scroll functionality, ensuring it scales proportionally.
- update the doc of adding`await` to `micropip.install` to prevent some warnings.
- Fix the behavior of the changelog modal on the datadoc page so that it no longer appends the document title upon popping up.
- Make the python cell/title uneditable for readonly views
> fix: some python cell bugs

- querybook/server/lib/query_analysis/templating.py
- querybook/tests/test_lib/test_query_analysis/test_templating.py
**Summary**
This PR addresses a vulnerability in the /ds/query_execution/templated_query/ endpoint of Querybook, where a Regular Expression used to escape SQL comments is vulnerable to ReDoS attacks.
**Impact**
The flaw allows an attacker to send malicious queries that can hang the server and consume excessive CPU resources, impacting availability.
**Reproduction Steps**
Attacker logs in and sends a crafted POST request to the endpoint.
The server hangs and CPU usage spikes to nearly 100%.
See the new test case as an example
**Root Cause**
The issue stems from the use of re.sub with a vulnerable regex pattern in the _escape_sql_comments function.
**Proposed Fix**
Replace the regex-based substitution with a non-regex alternative.
> fix: template query hangs with big payload

- querybook/webapp/components/DataDoc/DataDoc.scss
There needs to have space between the control buttons (comment button) and the above cell. 
The reason is there are no cell creation button to take the space, this fix is to add the height always.
Before
After
> fix: space between the cell and control buttons in readonly doc

- querybook/webapp/components/PythonKernelButton/PythonKernelButton.tsx
- querybook/webapp/lib/python/python-provider.tsx
- querybook/webapp/lib/python/usePython.ts
The issue: the kernel status will be cleared as idle when there is still pending tasks.
Fix: switch to derive the busy and idle status from the python execution status.
> fix: kernel status is incorrect with mutlipel task running

- querybook/server/tasks/disable_scheduled_docs.py
Fuzzy matching by name caused successes of another datadoc to be incorrectly included, which prevented a continuously failing datadoc from being disabled.
Use `get_task_run_record_run_by_name` instead to perform exact name matching and resolve this isssue.
> fix: get task run records by exact name when disabling datadoc

- package.json
- querybook/webapp/components/ChangeLog/ChangeLog.tsx
- querybook/webapp/components/EnvironmentAppRouter/modalRoute/ChangeLogRoute.tsx
issue: when the `Show Full View` user setting is enabled, the local store `change_log_last_viewed` will not be written, thus it will keep popping up the change log view.
fix: move the `localStore.set` into the change log view instead of only triggering on the modal dismiss.
> fix: change log auto popup bug

- package.json
- querybook/server/app/flask_app.py
- querybook/webapp/components/DataDocPythonCell/DataDocPythonCell.tsx
- querybook/webapp/components/PythonKernelButton/guide.md
- querybook/webapp/lib/python/python-provider.tsx
- querybook/webapp/lib/python/usePython.ts
- webpack.config.js
To cancel the Python run in a webworker, it needs to use [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements), which requires [cross-origin isolated](https://developer.mozilla.org/en-US/docs/Web/API/Window/crossOriginIsolated). But by enabling the required CSP headers, it will also block loading cross origin resources, e.g. to render some image from other sites.  So disabling this feature and update the user guide to reload the page for kernel restart if really needed.
> fix: disable cancel python run

- querybook/webapp/lib/python/python-provider.tsx
- querybook/webapp/lib/python/python-worker.ts
- querybook/webapp/lib/python/types.ts
- querybook/webapp/lib/python/usePython.ts
Disabled the cancel Python run feature in the PR https://github.com/pinterest/querybook/pull/1569, but didn't realize that `SharedArrrayBuffer` will be undefined when cross-origin is not isolated. Here to completely remove the related code.
Also remove the unused function of `createDataFrame` as we switched to use the code way `get_df`  to create dataframe from query result.
> fix: remove SharedArrayBuffer code

- querybook/server/lib/query_analysis/validation/decorators/base_sqlglot_validation_decorator.py
- querybook/server/lib/query_analysis/validation/decorators/metadata_decorators.py
- querybook/server/lib/query_analysis/validation/utils.py
- querybook/tests/test_lib/test_query_analysis/test_validation/test_validators/test_presto_optimizing_validator.py
Rationale: If fuzzy_table_name used for searching the correct table name is different from the invalid table_name in the query, the method `get_replacement_end_line_ch` can be overridden to supply the correct end_line/end_ch based on the query
> Make end_line, end_ch of table name suggestion variable

- querybook/server/lib/ai_assistant/assistants/openai_assistant.py
- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/webapp/components/AIAssistant/AutoFixButton.tsx
- requirements/ai/langchain.txt
- add two functions `_generate_sql_query` and `_query_auto_fix` in `base_ai_assistant` for plugin to override easlily
- upgrade new langchain packages
- add openai new models
> refactor: allow ai assistant plugin to override sql gen and fix

- querybook/server/lib/ai_assistant/base_ai_assistant.py
- querybook/server/lib/ai_assistant/tools/table_schema.py
- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/components/StatementExecutionBar/StatementExecutionBar.tsx
-  only show dataframe button when query run succeeds
- update to prefer data element's description over column description when getting table schema for ai assistant
- make the whole logic of `generate_sql_query` to be overridable, so that custom assistant can get query engine to do query validation.
- add tracking for the nlp search
> fix: copy dataframe button & refactor sql generation logic

- querybook/webapp/components/Search/SearchOverview.tsx
- querybook/webapp/redux/search/action.ts
- querybook/webapp/redux/search/reducer.ts
- querybook/webapp/redux/search/types.ts
renaming `useVectorSearch` as it looks like a react hook name.
> chore: rename useVectorSearch

- querybook/webapp/components/AIAssistant/AutoFixButton.tsx
- querybook/webapp/components/QueryEditor/QueryEditor.tsx
Fixes an issue where "Apply and Run" sometimes runs the old query due to getSelection() returning the full (potentially stale) query when nothing is selected. Now, getSelection() returns null if there’s no selection.
Also adds "Helpful" and "Unhelpful" buttons to the auto-fix modal when no fixed query is shown.
> fix: auto fix runs the old query

- package.json
- querybook/config/querybook_default_config.yaml
- querybook/server/app/flask_app.py
- querybook/server/env.py
Adds HTTP cache control for static assets (CSS, JS, images, fonts) to improve page load performance.
- Sets Cache-Control: public, max-age=604800, stale-while-revalidate=86400 on static files
- 7-days max-age and 1-day stale-while-revalidate for fast loading
> feat: add cache control for static assets

- Dockerfile
**Issue**
Docker builds were failing with "npm: not found" error due to recent changes in the Python base image packaging.
**Fix**
Fix by pinning to python:3.10-bookworm to ensure consistent Node.js/npm availability.
> fix: pin Docker base image to python:3.10-bookworm
